// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: badimage.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBadImages = `-- name: CountBadImages :one
SELECT COUNT(*) FROM bad_images
`

func (q *Queries) CountBadImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBadImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBadImagesByCategory = `-- name: CountBadImagesByCategory :one
SELECT COUNT(*) FROM bad_images WHERE category = $1
`

func (q *Queries) CountBadImagesByCategory(ctx context.Context, category pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countBadImagesByCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBadImage = `-- name: CreateBadImage :one
INSERT INTO bad_images (phash, category, nsfw_score, source_url, added_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (phash) DO UPDATE SET
    nsfw_score = EXCLUDED.nsfw_score,
    updated_at = NOW()
RETURNING id, phash, category, nsfw_score, source_url, added_by, created_at, updated_at
`

type CreateBadImageParams struct {
	Phash     int64         `json:"phash"`
	Category  pgtype.Text   `json:"category"`
	NsfwScore pgtype.Float8 `json:"nsfw_score"`
	SourceUrl pgtype.Text   `json:"source_url"`
	AddedBy   pgtype.Text   `json:"added_by"`
}

func (q *Queries) CreateBadImage(ctx context.Context, arg CreateBadImageParams) (BadImage, error) {
	row := q.db.QueryRow(ctx, createBadImage,
		arg.Phash,
		arg.Category,
		arg.NsfwScore,
		arg.SourceUrl,
		arg.AddedBy,
	)
	var i BadImage
	err := row.Scan(
		&i.ID,
		&i.Phash,
		&i.Category,
		&i.NsfwScore,
		&i.SourceUrl,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBadImage = `-- name: DeleteBadImage :exec
DELETE FROM bad_images WHERE phash = $1
`

func (q *Queries) DeleteBadImage(ctx context.Context, phash int64) error {
	_, err := q.db.Exec(ctx, deleteBadImage, phash)
	return err
}

const getBadImageByPHash = `-- name: GetBadImageByPHash :one
SELECT id, phash, category, nsfw_score, source_url, added_by, created_at, updated_at FROM bad_images WHERE phash = $1
`

func (q *Queries) GetBadImageByPHash(ctx context.Context, phash int64) (BadImage, error) {
	row := q.db.QueryRow(ctx, getBadImageByPHash, phash)
	var i BadImage
	err := row.Scan(
		&i.ID,
		&i.Phash,
		&i.Category,
		&i.NsfwScore,
		&i.SourceUrl,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBadImagesByPHashes = `-- name: GetBadImagesByPHashes :many
SELECT id, phash, category, nsfw_score, source_url, added_by, created_at, updated_at FROM bad_images WHERE phash = ANY($1::bigint[])
`

func (q *Queries) GetBadImagesByPHashes(ctx context.Context, dollar_1 []int64) ([]BadImage, error) {
	rows, err := q.db.Query(ctx, getBadImagesByPHashes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BadImage
	for rows.Next() {
		var i BadImage
		if err := rows.Scan(
			&i.ID,
			&i.Phash,
			&i.Category,
			&i.NsfwScore,
			&i.SourceUrl,
			&i.AddedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBadImages = `-- name: ListAllBadImages :many
SELECT id, phash, category, nsfw_score, source_url, added_by, created_at, updated_at FROM bad_images
`

func (q *Queries) ListAllBadImages(ctx context.Context) ([]BadImage, error) {
	rows, err := q.db.Query(ctx, listAllBadImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BadImage
	for rows.Next() {
		var i BadImage
		if err := rows.Scan(
			&i.ID,
			&i.Phash,
			&i.Category,
			&i.NsfwScore,
			&i.SourceUrl,
			&i.AddedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBadImagesByCategory = `-- name: ListBadImagesByCategory :many
SELECT id, phash, category, nsfw_score, source_url, added_by, created_at, updated_at FROM bad_images
WHERE category = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBadImagesByCategoryParams struct {
	Category pgtype.Text `json:"category"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListBadImagesByCategory(ctx context.Context, arg ListBadImagesByCategoryParams) ([]BadImage, error) {
	rows, err := q.db.Query(ctx, listBadImagesByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BadImage
	for rows.Next() {
		var i BadImage
		if err := rows.Scan(
			&i.ID,
			&i.Phash,
			&i.Category,
			&i.NsfwScore,
			&i.SourceUrl,
			&i.AddedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
