// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: badword.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBadWords = `-- name: CountBadWords :one
SELECT COUNT(*) FROM bad_words
`

func (q *Queries) CountBadWords(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBadWords)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBadWordsByCategory = `-- name: CountBadWordsByCategory :one
SELECT COUNT(*) FROM bad_words WHERE category = $1
`

func (q *Queries) CountBadWordsByCategory(ctx context.Context, category pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countBadWordsByCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBadWord = `-- name: CreateBadWord :one
INSERT INTO bad_words (word, category, severity, added_by)
VALUES ($1, $2, $3, $4)
RETURNING id, word, category, severity, added_by, created_at, updated_at
`

type CreateBadWordParams struct {
	Word     string      `json:"word"`
	Category pgtype.Text `json:"category"`
	Severity pgtype.Int4 `json:"severity"`
	AddedBy  pgtype.Text `json:"added_by"`
}

func (q *Queries) CreateBadWord(ctx context.Context, arg CreateBadWordParams) (BadWord, error) {
	row := q.db.QueryRow(ctx, createBadWord,
		arg.Word,
		arg.Category,
		arg.Severity,
		arg.AddedBy,
	)
	var i BadWord
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Category,
		&i.Severity,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBadWord = `-- name: DeleteBadWord :exec
DELETE FROM bad_words WHERE word = $1
`

func (q *Queries) DeleteBadWord(ctx context.Context, word string) error {
	_, err := q.db.Exec(ctx, deleteBadWord, word)
	return err
}

const getBadWordByID = `-- name: GetBadWordByID :one
SELECT id, word, category, severity, added_by, created_at, updated_at FROM bad_words WHERE id = $1
`

func (q *Queries) GetBadWordByID(ctx context.Context, id int64) (BadWord, error) {
	row := q.db.QueryRow(ctx, getBadWordByID, id)
	var i BadWord
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Category,
		&i.Severity,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBadWordByWord = `-- name: GetBadWordByWord :one
SELECT id, word, category, severity, added_by, created_at, updated_at FROM bad_words WHERE word = $1
`

func (q *Queries) GetBadWordByWord(ctx context.Context, word string) (BadWord, error) {
	row := q.db.QueryRow(ctx, getBadWordByWord, word)
	var i BadWord
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Category,
		&i.Severity,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllBadWords = `-- name: ListAllBadWords :many
SELECT id, word, category, severity, added_by, created_at, updated_at FROM bad_words
`

func (q *Queries) ListAllBadWords(ctx context.Context) ([]BadWord, error) {
	rows, err := q.db.Query(ctx, listAllBadWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BadWord
	for rows.Next() {
		var i BadWord
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Category,
			&i.Severity,
			&i.AddedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBadWords = `-- name: ListBadWords :many
SELECT id, word, category, severity, added_by, created_at, updated_at FROM bad_words
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBadWordsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBadWords(ctx context.Context, arg ListBadWordsParams) ([]BadWord, error) {
	rows, err := q.db.Query(ctx, listBadWords, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BadWord
	for rows.Next() {
		var i BadWord
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Category,
			&i.Severity,
			&i.AddedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBadWordsByCategory = `-- name: ListBadWordsByCategory :many
SELECT id, word, category, severity, added_by, created_at, updated_at FROM bad_words
WHERE category = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBadWordsByCategoryParams struct {
	Category pgtype.Text `json:"category"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListBadWordsByCategory(ctx context.Context, arg ListBadWordsByCategoryParams) ([]BadWord, error) {
	rows, err := q.db.Query(ctx, listBadWordsByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BadWord
	for rows.Next() {
		var i BadWord
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Category,
			&i.Severity,
			&i.AddedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBadWord = `-- name: UpdateBadWord :one
UPDATE bad_words
SET word = $2, category = $3, severity = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, word, category, severity, added_by, created_at, updated_at
`

type UpdateBadWordParams struct {
	ID       int64       `json:"id"`
	Word     string      `json:"word"`
	Category pgtype.Text `json:"category"`
	Severity pgtype.Int4 `json:"severity"`
}

func (q *Queries) UpdateBadWord(ctx context.Context, arg UpdateBadWordParams) (BadWord, error) {
	row := q.db.QueryRow(ctx, updateBadWord,
		arg.ID,
		arg.Word,
		arg.Category,
		arg.Severity,
	)
	var i BadWord
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Category,
		&i.Severity,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
