// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AutoResetQuotaDefault(ctx context.Context, arg AutoResetQuotaDefaultParams) error
	CountPlans(ctx context.Context) (int64, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	ExpireSubscription(ctx context.Context, arg ExpireSubscriptionParams) error
	ExpireSubscriptions(ctx context.Context, arg ExpireSubscriptionsParams) error
	GetPlanByID(ctx context.Context, id int64) (Plan, error)
	GetPlans(ctx context.Context) ([]Plan, error)
	GetPlansFirstPage(ctx context.Context, limit int32) ([]Plan, error)
	GetPlansWithCursor(ctx context.Context, arg GetPlansWithCursorParams) ([]Plan, error)
	GetPlansWithOffset(ctx context.Context, arg GetPlansWithOffsetParams) ([]Plan, error)
	GetSubscriptionByID(ctx context.Context, id int64) (Subscription, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	UpdateStorageAudioUsed(ctx context.Context, arg UpdateStorageAudioUsedParams) error
	UpdateStorageCompressUsed(ctx context.Context, arg UpdateStorageCompressUsedParams) error
	UpdateStorageDocumentUsed(ctx context.Context, arg UpdateStorageDocumentUsedParams) error
	UpdateStorageOtherUsed(ctx context.Context, arg UpdateStorageOtherUsedParams) error
	UpdateStoragePhotosUsed(ctx context.Context, arg UpdateStoragePhotosUsedParams) error
	UpdateStorageVideoUsed(ctx context.Context, arg UpdateStorageVideoUsedParams) error
	UpdateUserStorage(ctx context.Context, arg UpdateUserStorageParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
