// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountBadImages(ctx context.Context) (int64, error)
	CountBadImagesByCategory(ctx context.Context, category pgtype.Text) (int64, error)
	CountBadWords(ctx context.Context) (int64, error)
	CountBadWordsByCategory(ctx context.Context, category pgtype.Text) (int64, error)
	CreateBadImage(ctx context.Context, arg CreateBadImageParams) (BadImage, error)
	CreateBadWord(ctx context.Context, arg CreateBadWordParams) (BadWord, error)
	DeleteBadImage(ctx context.Context, phash int64) error
	DeleteBadWord(ctx context.Context, word string) error
	GetBadImageByPHash(ctx context.Context, phash int64) (BadImage, error)
	GetBadImagesByPHashes(ctx context.Context, dollar_1 []int64) ([]BadImage, error)
	GetBadWordByID(ctx context.Context, id int64) (BadWord, error)
	GetBadWordByWord(ctx context.Context, word string) (BadWord, error)
	ListAllBadImages(ctx context.Context) ([]BadImage, error)
	ListAllBadWords(ctx context.Context) ([]BadWord, error)
	ListBadImagesByCategory(ctx context.Context, arg ListBadImagesByCategoryParams) ([]BadImage, error)
	ListBadWords(ctx context.Context, arg ListBadWordsParams) ([]BadWord, error)
	ListBadWordsByCategory(ctx context.Context, arg ListBadWordsByCategoryParams) ([]BadWord, error)
	UpdateBadWord(ctx context.Context, arg UpdateBadWordParams) (BadWord, error)
}

var _ Querier = (*Queries)(nil)
