// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: moderation/v1/admin.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Admin messages
type AddBadWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	NsfwScore     float64                `protobuf:"fixed64,3,opt,name=nsfw_score,json=nsfwScore,proto3" json:"nsfw_score,omitempty"`
	AddedBy       *string                `protobuf:"bytes,4,opt,name=added_by,json=addedBy,proto3,oneof" json:"added_by,omitempty"`
	ModelVersion  *string                `protobuf:"bytes,5,opt,name=model_version,json=modelVersion,proto3,oneof" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBadWordRequest) Reset() {
	*x = AddBadWordRequest{}
	mi := &file_moderation_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBadWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBadWordRequest) ProtoMessage() {}

func (x *AddBadWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBadWordRequest.ProtoReflect.Descriptor instead.
func (*AddBadWordRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AddBadWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *AddBadWordRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AddBadWordRequest) GetNsfwScore() float64 {
	if x != nil {
		return x.NsfwScore
	}
	return 0
}

func (x *AddBadWordRequest) GetAddedBy() string {
	if x != nil && x.AddedBy != nil {
		return *x.AddedBy
	}
	return ""
}

func (x *AddBadWordRequest) GetModelVersion() string {
	if x != nil && x.ModelVersion != nil {
		return *x.ModelVersion
	}
	return ""
}

type AddBadWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBadWordResponse) Reset() {
	*x = AddBadWordResponse{}
	mi := &file_moderation_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBadWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBadWordResponse) ProtoMessage() {}

func (x *AddBadWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBadWordResponse.ProtoReflect.Descriptor instead.
func (*AddBadWordResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AddBadWordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddBadWordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveBadWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBadWordRequest) Reset() {
	*x = RemoveBadWordRequest{}
	mi := &file_moderation_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBadWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBadWordRequest) ProtoMessage() {}

func (x *RemoveBadWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBadWordRequest.ProtoReflect.Descriptor instead.
func (*RemoveBadWordRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveBadWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type RemoveBadWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBadWordResponse) Reset() {
	*x = RemoveBadWordResponse{}
	mi := &file_moderation_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBadWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBadWordResponse) ProtoMessage() {}

func (x *RemoveBadWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBadWordResponse.ProtoReflect.Descriptor instead.
func (*RemoveBadWordResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveBadWordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveBadWordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListBadWordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBadWordsRequest) Reset() {
	*x = ListBadWordsRequest{}
	mi := &file_moderation_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBadWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBadWordsRequest) ProtoMessage() {}

func (x *ListBadWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBadWordsRequest.ProtoReflect.Descriptor instead.
func (*ListBadWordsRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListBadWordsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListBadWordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBadWordsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListBadWordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Words         []*BadWordEntry        `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBadWordsResponse) Reset() {
	*x = ListBadWordsResponse{}
	mi := &file_moderation_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBadWordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBadWordsResponse) ProtoMessage() {}

func (x *ListBadWordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBadWordsResponse.ProtoReflect.Descriptor instead.
func (*ListBadWordsResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListBadWordsResponse) GetWords() []*BadWordEntry {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *ListBadWordsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BadWordEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	NsfwScore     float64                `protobuf:"fixed64,3,opt,name=nsfw_score,json=nsfwScore,proto3" json:"nsfw_score,omitempty"`
	AddedBy       *string                `protobuf:"bytes,4,opt,name=added_by,json=addedBy,proto3,oneof" json:"added_by,omitempty"`
	ModelVersion  *string                `protobuf:"bytes,5,opt,name=model_version,json=modelVersion,proto3,oneof" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadWordEntry) Reset() {
	*x = BadWordEntry{}
	mi := &file_moderation_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadWordEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadWordEntry) ProtoMessage() {}

func (x *BadWordEntry) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadWordEntry.ProtoReflect.Descriptor instead.
func (*BadWordEntry) Descriptor() ([]byte, []int) {
	return file_moderation_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *BadWordEntry) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *BadWordEntry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BadWordEntry) GetNsfwScore() float64 {
	if x != nil {
		return x.NsfwScore
	}
	return 0
}

func (x *BadWordEntry) GetAddedBy() string {
	if x != nil && x.AddedBy != nil {
		return *x.AddedBy
	}
	return ""
}

func (x *BadWordEntry) GetModelVersion() string {
	if x != nil && x.ModelVersion != nil {
		return *x.ModelVersion
	}
	return ""
}

type RebuildBloomFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildBloomFilterRequest) Reset() {
	*x = RebuildBloomFilterRequest{}
	mi := &file_moderation_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildBloomFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildBloomFilterRequest) ProtoMessage() {}

func (x *RebuildBloomFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildBloomFilterRequest.ProtoReflect.Descriptor instead.
func (*RebuildBloomFilterRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_admin_proto_rawDescGZIP(), []int{7}
}

type RebuildBloomFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WordsCount    int32                  `protobuf:"varint,3,opt,name=words_count,json=wordsCount,proto3" json:"words_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildBloomFilterResponse) Reset() {
	*x = RebuildBloomFilterResponse{}
	mi := &file_moderation_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildBloomFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildBloomFilterResponse) ProtoMessage() {}

func (x *RebuildBloomFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildBloomFilterResponse.ProtoReflect.Descriptor instead.
func (*RebuildBloomFilterResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *RebuildBloomFilterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RebuildBloomFilterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RebuildBloomFilterResponse) GetWordsCount() int32 {
	if x != nil {
		return x.WordsCount
	}
	return 0
}

var File_moderation_v1_admin_proto protoreflect.FileDescriptor

const file_moderation_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x19moderation/v1/admin.proto\x12\rmoderation.v1\x1a\x1cgoogle/api/annotations.proto\"\xcb\x01\n" +
	"\x11AddBadWordRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"nsfw_score\x18\x03 \x01(\x01R\tnsfwScore\x12\x1e\n" +
	"\badded_by\x18\x04 \x01(\tH\x00R\aaddedBy\x88\x01\x01\x12(\n" +
	"\rmodel_version\x18\x05 \x01(\tH\x01R\fmodelVersion\x88\x01\x01B\v\n" +
	"\t_added_byB\x10\n" +
	"\x0e_model_version\"H\n" +
	"\x12AddBadWordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x14RemoveBadWordRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\"K\n" +
	"\x15RemoveBadWordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\x13ListBadWordsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"_\n" +
	"\x14ListBadWordsResponse\x121\n" +
	"\x05words\x18\x01 \x03(\v2\x1b.moderation.v1.BadWordEntryR\x05words\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc6\x01\n" +
	"\fBadWordEntry\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"nsfw_score\x18\x03 \x01(\x01R\tnsfwScore\x12\x1e\n" +
	"\badded_by\x18\x04 \x01(\tH\x00R\aaddedBy\x88\x01\x01\x12(\n" +
	"\rmodel_version\x18\x05 \x01(\tH\x01R\fmodelVersion\x88\x01\x01B\v\n" +
	"\t_added_byB\x10\n" +
	"\x0e_model_version\"\x1b\n" +
	"\x19RebuildBloomFilterRequest\"q\n" +
	"\x1aRebuildBloomFilterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vwords_count\x18\x03 \x01(\x05R\n" +
	"wordsCount2\x95\x04\n" +
	"\fAdminService\x12t\n" +
	"\n" +
	"AddBadWord\x12 .moderation.v1.AddBadWordRequest\x1a!.moderation.v1.AddBadWordResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/admin/badwords\x12\x81\x01\n" +
	"\rRemoveBadWord\x12#.moderation.v1.RemoveBadWordRequest\x1a$.moderation.v1.RemoveBadWordResponse\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/api/v1/admin/badwords/{word}\x12w\n" +
	"\fListBadWords\x12\".moderation.v1.ListBadWordsRequest\x1a#.moderation.v1.ListBadWordsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/admin/badwords\x12\x91\x01\n" +
	"\x12RebuildBloomFilter\x12(.moderation.v1.RebuildBloomFilterRequest\x1a).moderation.v1.RebuildBloomFilterResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/admin/bloom/rebuildBD\n" +
	"\rmoderation.v1P\x01Z\x1fmoderation/api/moderation/v1;v1\xa2\x02\x0fAPImoderationV1b\x06proto3"

var (
	file_moderation_v1_admin_proto_rawDescOnce sync.Once
	file_moderation_v1_admin_proto_rawDescData []byte
)

func file_moderation_v1_admin_proto_rawDescGZIP() []byte {
	file_moderation_v1_admin_proto_rawDescOnce.Do(func() {
		file_moderation_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moderation_v1_admin_proto_rawDesc), len(file_moderation_v1_admin_proto_rawDesc)))
	})
	return file_moderation_v1_admin_proto_rawDescData
}

var file_moderation_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_moderation_v1_admin_proto_goTypes = []any{
	(*AddBadWordRequest)(nil),          // 0: moderation.v1.AddBadWordRequest
	(*AddBadWordResponse)(nil),         // 1: moderation.v1.AddBadWordResponse
	(*RemoveBadWordRequest)(nil),       // 2: moderation.v1.RemoveBadWordRequest
	(*RemoveBadWordResponse)(nil),      // 3: moderation.v1.RemoveBadWordResponse
	(*ListBadWordsRequest)(nil),        // 4: moderation.v1.ListBadWordsRequest
	(*ListBadWordsResponse)(nil),       // 5: moderation.v1.ListBadWordsResponse
	(*BadWordEntry)(nil),               // 6: moderation.v1.BadWordEntry
	(*RebuildBloomFilterRequest)(nil),  // 7: moderation.v1.RebuildBloomFilterRequest
	(*RebuildBloomFilterResponse)(nil), // 8: moderation.v1.RebuildBloomFilterResponse
}
var file_moderation_v1_admin_proto_depIdxs = []int32{
	6, // 0: moderation.v1.ListBadWordsResponse.words:type_name -> moderation.v1.BadWordEntry
	0, // 1: moderation.v1.AdminService.AddBadWord:input_type -> moderation.v1.AddBadWordRequest
	2, // 2: moderation.v1.AdminService.RemoveBadWord:input_type -> moderation.v1.RemoveBadWordRequest
	4, // 3: moderation.v1.AdminService.ListBadWords:input_type -> moderation.v1.ListBadWordsRequest
	7, // 4: moderation.v1.AdminService.RebuildBloomFilter:input_type -> moderation.v1.RebuildBloomFilterRequest
	1, // 5: moderation.v1.AdminService.AddBadWord:output_type -> moderation.v1.AddBadWordResponse
	3, // 6: moderation.v1.AdminService.RemoveBadWord:output_type -> moderation.v1.RemoveBadWordResponse
	5, // 7: moderation.v1.AdminService.ListBadWords:output_type -> moderation.v1.ListBadWordsResponse
	8, // 8: moderation.v1.AdminService.RebuildBloomFilter:output_type -> moderation.v1.RebuildBloomFilterResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_moderation_v1_admin_proto_init() }
func file_moderation_v1_admin_proto_init() {
	if File_moderation_v1_admin_proto != nil {
		return
	}
	file_moderation_v1_admin_proto_msgTypes[0].OneofWrappers = []any{}
	file_moderation_v1_admin_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moderation_v1_admin_proto_rawDesc), len(file_moderation_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moderation_v1_admin_proto_goTypes,
		DependencyIndexes: file_moderation_v1_admin_proto_depIdxs,
		MessageInfos:      file_moderation_v1_admin_proto_msgTypes,
	}.Build()
	File_moderation_v1_admin_proto = out.File
	file_moderation_v1_admin_proto_goTypes = nil
	file_moderation_v1_admin_proto_depIdxs = nil
}
