// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.12.4
// source: moderation/v1/admin.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAdminServiceAddBadWord = "/moderation.v1.AdminService/AddBadWord"
const OperationAdminServiceListBadWords = "/moderation.v1.AdminService/ListBadWords"
const OperationAdminServiceRebuildBloomFilter = "/moderation.v1.AdminService/RebuildBloomFilter"
const OperationAdminServiceRemoveBadWord = "/moderation.v1.AdminService/RemoveBadWord"

type AdminServiceHTTPServer interface {
	// AddBadWord AddBadWord adds a word to the blocklist.
	AddBadWord(context.Context, *AddBadWordRequest) (*AddBadWordResponse, error)
	// ListBadWords ListBadWords lists all bad words.
	ListBadWords(context.Context, *ListBadWordsRequest) (*ListBadWordsResponse, error)
	// RebuildBloomFilter RebuildBloomFilter rebuilds the bloom filter.
	RebuildBloomFilter(context.Context, *RebuildBloomFilterRequest) (*RebuildBloomFilterResponse, error)
	// RemoveBadWord RemoveBadWord removes a word from the blocklist.
	RemoveBadWord(context.Context, *RemoveBadWordRequest) (*RemoveBadWordResponse, error)
}

func RegisterAdminServiceHTTPServer(s *http.Server, srv AdminServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/admin/badwords", _AdminService_AddBadWord0_HTTP_Handler(srv))
	r.DELETE("/api/v1/admin/badwords/{word}", _AdminService_RemoveBadWord0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/badwords", _AdminService_ListBadWords0_HTTP_Handler(srv))
	r.POST("/api/v1/admin/bloom/rebuild", _AdminService_RebuildBloomFilter0_HTTP_Handler(srv))
}

func _AdminService_AddBadWord0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddBadWordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceAddBadWord)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddBadWord(ctx, req.(*AddBadWordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddBadWordResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_RemoveBadWord0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveBadWordRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceRemoveBadWord)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveBadWord(ctx, req.(*RemoveBadWordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveBadWordResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListBadWords0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBadWordsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListBadWords)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBadWords(ctx, req.(*ListBadWordsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBadWordsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_RebuildBloomFilter0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RebuildBloomFilterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceRebuildBloomFilter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RebuildBloomFilter(ctx, req.(*RebuildBloomFilterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RebuildBloomFilterResponse)
		return ctx.Result(200, reply)
	}
}

type AdminServiceHTTPClient interface {
	// AddBadWord AddBadWord adds a word to the blocklist.
	AddBadWord(ctx context.Context, req *AddBadWordRequest, opts ...http.CallOption) (rsp *AddBadWordResponse, err error)
	// ListBadWords ListBadWords lists all bad words.
	ListBadWords(ctx context.Context, req *ListBadWordsRequest, opts ...http.CallOption) (rsp *ListBadWordsResponse, err error)
	// RebuildBloomFilter RebuildBloomFilter rebuilds the bloom filter.
	RebuildBloomFilter(ctx context.Context, req *RebuildBloomFilterRequest, opts ...http.CallOption) (rsp *RebuildBloomFilterResponse, err error)
	// RemoveBadWord RemoveBadWord removes a word from the blocklist.
	RemoveBadWord(ctx context.Context, req *RemoveBadWordRequest, opts ...http.CallOption) (rsp *RemoveBadWordResponse, err error)
}

type AdminServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminServiceHTTPClient(client *http.Client) AdminServiceHTTPClient {
	return &AdminServiceHTTPClientImpl{client}
}

// AddBadWord AddBadWord adds a word to the blocklist.
func (c *AdminServiceHTTPClientImpl) AddBadWord(ctx context.Context, in *AddBadWordRequest, opts ...http.CallOption) (*AddBadWordResponse, error) {
	var out AddBadWordResponse
	pattern := "/api/v1/admin/badwords"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceAddBadWord))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListBadWords ListBadWords lists all bad words.
func (c *AdminServiceHTTPClientImpl) ListBadWords(ctx context.Context, in *ListBadWordsRequest, opts ...http.CallOption) (*ListBadWordsResponse, error) {
	var out ListBadWordsResponse
	pattern := "/api/v1/admin/badwords"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceListBadWords))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RebuildBloomFilter RebuildBloomFilter rebuilds the bloom filter.
func (c *AdminServiceHTTPClientImpl) RebuildBloomFilter(ctx context.Context, in *RebuildBloomFilterRequest, opts ...http.CallOption) (*RebuildBloomFilterResponse, error) {
	var out RebuildBloomFilterResponse
	pattern := "/api/v1/admin/bloom/rebuild"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceRebuildBloomFilter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveBadWord RemoveBadWord removes a word from the blocklist.
func (c *AdminServiceHTTPClientImpl) RemoveBadWord(ctx context.Context, in *RemoveBadWordRequest, opts ...http.CallOption) (*RemoveBadWordResponse, error) {
	var out RemoveBadWordResponse
	pattern := "/api/v1/admin/badwords/{word}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceRemoveBadWord))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
