// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: moderation/v1/moderation.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModerationService_Moderate_FullMethodName      = "/moderation.v1.ModerationService/Moderate"
	ModerationService_ModerateText_FullMethodName  = "/moderation.v1.ModerationService/ModerateText"
	ModerationService_ModerateImage_FullMethodName = "/moderation.v1.ModerationService/ModerateImage"
	ModerationService_ModerateVideo_FullMethodName = "/moderation.v1.ModerationService/ModerateVideo"
	ModerationService_ModerateAudio_FullMethodName = "/moderation.v1.ModerationService/ModerateAudio"
	ModerationService_BatchModerate_FullMethodName = "/moderation.v1.ModerationService/BatchModerate"
)

// ModerationServiceClient is the client API for ModerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModerationService provides content moderation for posts and comments.
type ModerationServiceClient interface {
	Moderate(ctx context.Context, in *ModerateRequest, opts ...grpc.CallOption) (*ModerationResponse, error)
	// ModerateText checks a text for harmful content.
	ModerateText(ctx context.Context, in *ModerateTextRequest, opts ...grpc.CallOption) (*ModerationResponse, error)
	// ModerateImage checks an image for harmful content.
	ModerateImage(ctx context.Context, in *ModerateImageRequest, opts ...grpc.CallOption) (*ModerationResponse, error)
	// ModerateVideo checks an video for harmful content.
	ModerateVideo(ctx context.Context, in *ModerateVideoRequest, opts ...grpc.CallOption) (*ModerationResponse, error)
	// ModerateAudio checks an audio for harmful content.
	ModerateAudio(ctx context.Context, in *ModerateAudioRequest, opts ...grpc.CallOption) (*ModerationResponse, error)
	// BatchModerate checks multiple items at once.
	BatchModerate(ctx context.Context, in *BatchModerateRequest, opts ...grpc.CallOption) (*BatchModerateResponse, error)
}

type moderationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModerationServiceClient(cc grpc.ClientConnInterface) ModerationServiceClient {
	return &moderationServiceClient{cc}
}

func (c *moderationServiceClient) Moderate(ctx context.Context, in *ModerateRequest, opts ...grpc.CallOption) (*ModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModerationResponse)
	err := c.cc.Invoke(ctx, ModerationService_Moderate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ModerateText(ctx context.Context, in *ModerateTextRequest, opts ...grpc.CallOption) (*ModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModerationResponse)
	err := c.cc.Invoke(ctx, ModerationService_ModerateText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ModerateImage(ctx context.Context, in *ModerateImageRequest, opts ...grpc.CallOption) (*ModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModerationResponse)
	err := c.cc.Invoke(ctx, ModerationService_ModerateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ModerateVideo(ctx context.Context, in *ModerateVideoRequest, opts ...grpc.CallOption) (*ModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModerationResponse)
	err := c.cc.Invoke(ctx, ModerationService_ModerateVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ModerateAudio(ctx context.Context, in *ModerateAudioRequest, opts ...grpc.CallOption) (*ModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModerationResponse)
	err := c.cc.Invoke(ctx, ModerationService_ModerateAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) BatchModerate(ctx context.Context, in *BatchModerateRequest, opts ...grpc.CallOption) (*BatchModerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchModerateResponse)
	err := c.cc.Invoke(ctx, ModerationService_BatchModerate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModerationServiceServer is the server API for ModerationService service.
// All implementations must embed UnimplementedModerationServiceServer
// for forward compatibility.
//
// ModerationService provides content moderation for posts and comments.
type ModerationServiceServer interface {
	Moderate(context.Context, *ModerateRequest) (*ModerationResponse, error)
	// ModerateText checks a text for harmful content.
	ModerateText(context.Context, *ModerateTextRequest) (*ModerationResponse, error)
	// ModerateImage checks an image for harmful content.
	ModerateImage(context.Context, *ModerateImageRequest) (*ModerationResponse, error)
	// ModerateVideo checks an video for harmful content.
	ModerateVideo(context.Context, *ModerateVideoRequest) (*ModerationResponse, error)
	// ModerateAudio checks an audio for harmful content.
	ModerateAudio(context.Context, *ModerateAudioRequest) (*ModerationResponse, error)
	// BatchModerate checks multiple items at once.
	BatchModerate(context.Context, *BatchModerateRequest) (*BatchModerateResponse, error)
	mustEmbedUnimplementedModerationServiceServer()
}

// UnimplementedModerationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModerationServiceServer struct{}

func (UnimplementedModerationServiceServer) Moderate(context.Context, *ModerateRequest) (*ModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Moderate not implemented")
}
func (UnimplementedModerationServiceServer) ModerateText(context.Context, *ModerateTextRequest) (*ModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModerateText not implemented")
}
func (UnimplementedModerationServiceServer) ModerateImage(context.Context, *ModerateImageRequest) (*ModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModerateImage not implemented")
}
func (UnimplementedModerationServiceServer) ModerateVideo(context.Context, *ModerateVideoRequest) (*ModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModerateVideo not implemented")
}
func (UnimplementedModerationServiceServer) ModerateAudio(context.Context, *ModerateAudioRequest) (*ModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModerateAudio not implemented")
}
func (UnimplementedModerationServiceServer) BatchModerate(context.Context, *BatchModerateRequest) (*BatchModerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchModerate not implemented")
}
func (UnimplementedModerationServiceServer) mustEmbedUnimplementedModerationServiceServer() {}
func (UnimplementedModerationServiceServer) testEmbeddedByValue()                           {}

// UnsafeModerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModerationServiceServer will
// result in compilation errors.
type UnsafeModerationServiceServer interface {
	mustEmbedUnimplementedModerationServiceServer()
}

func RegisterModerationServiceServer(s grpc.ServiceRegistrar, srv ModerationServiceServer) {
	// If the following call panics, it indicates UnimplementedModerationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModerationService_ServiceDesc, srv)
}

func _ModerationService_Moderate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).Moderate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_Moderate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).Moderate(ctx, req.(*ModerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ModerateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModerateTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ModerateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ModerateText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ModerateText(ctx, req.(*ModerateTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ModerateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModerateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ModerateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ModerateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ModerateImage(ctx, req.(*ModerateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ModerateVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModerateVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ModerateVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ModerateVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ModerateVideo(ctx, req.(*ModerateVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ModerateAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModerateAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ModerateAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ModerateAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ModerateAudio(ctx, req.(*ModerateAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_BatchModerate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchModerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).BatchModerate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_BatchModerate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).BatchModerate(ctx, req.(*BatchModerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModerationService_ServiceDesc is the grpc.ServiceDesc for ModerationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModerationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moderation.v1.ModerationService",
	HandlerType: (*ModerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Moderate",
			Handler:    _ModerationService_Moderate_Handler,
		},
		{
			MethodName: "ModerateText",
			Handler:    _ModerationService_ModerateText_Handler,
		},
		{
			MethodName: "ModerateImage",
			Handler:    _ModerationService_ModerateImage_Handler,
		},
		{
			MethodName: "ModerateVideo",
			Handler:    _ModerationService_ModerateVideo_Handler,
		},
		{
			MethodName: "ModerateAudio",
			Handler:    _ModerationService_ModerateAudio_Handler,
		},
		{
			MethodName: "BatchModerate",
			Handler:    _ModerationService_BatchModerate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moderation/v1/moderation.proto",
}
