// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.4
// source: moderation/v1/moderation.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationModerationServiceBatchModerate = "/moderation.v1.ModerationService/BatchModerate"
const OperationModerationServiceModerateComment = "/moderation.v1.ModerationService/ModerateComment"
const OperationModerationServiceModeratePost = "/moderation.v1.ModerationService/ModeratePost"

type ModerationServiceHTTPServer interface {
	// BatchModerate BatchModerate checks multiple items at once.
	BatchModerate(context.Context, *BatchModerateRequest) (*BatchModerateResponse, error)
	// ModerateComment ModerateComment checks a comment for harmful content.
	ModerateComment(context.Context, *ModerateCommentRequest) (*ModerationResponse, error)
	// ModeratePost ModeratePost checks a post for harmful content.
	ModeratePost(context.Context, *ModeratePostRequest) (*ModerationResponse, error)
}

func RegisterModerationServiceHTTPServer(s *http.Server, srv ModerationServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/moderate/post", _ModerationService_ModeratePost0_HTTP_Handler(srv))
	r.POST("/api/v1/moderate/comment", _ModerationService_ModerateComment0_HTTP_Handler(srv))
	r.POST("/api/v1/moderate/batch", _ModerationService_BatchModerate0_HTTP_Handler(srv))
}

func _ModerationService_ModeratePost0_HTTP_Handler(srv ModerationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ModeratePostRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModerationServiceModeratePost)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ModeratePost(ctx, req.(*ModeratePostRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ModerationResponse)
		return ctx.Result(200, reply)
	}
}

func _ModerationService_ModerateComment0_HTTP_Handler(srv ModerationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ModerateCommentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModerationServiceModerateComment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ModerateComment(ctx, req.(*ModerateCommentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ModerationResponse)
		return ctx.Result(200, reply)
	}
}

func _ModerationService_BatchModerate0_HTTP_Handler(srv ModerationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchModerateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModerationServiceBatchModerate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchModerate(ctx, req.(*BatchModerateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchModerateResponse)
		return ctx.Result(200, reply)
	}
}

type ModerationServiceHTTPClient interface {
	// BatchModerate BatchModerate checks multiple items at once.
	BatchModerate(ctx context.Context, req *BatchModerateRequest, opts ...http.CallOption) (rsp *BatchModerateResponse, err error)
	// ModerateComment ModerateComment checks a comment for harmful content.
	ModerateComment(ctx context.Context, req *ModerateCommentRequest, opts ...http.CallOption) (rsp *ModerationResponse, err error)
	// ModeratePost ModeratePost checks a post for harmful content.
	ModeratePost(ctx context.Context, req *ModeratePostRequest, opts ...http.CallOption) (rsp *ModerationResponse, err error)
}

type ModerationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewModerationServiceHTTPClient(client *http.Client) ModerationServiceHTTPClient {
	return &ModerationServiceHTTPClientImpl{client}
}

// BatchModerate BatchModerate checks multiple items at once.
func (c *ModerationServiceHTTPClientImpl) BatchModerate(ctx context.Context, in *BatchModerateRequest, opts ...http.CallOption) (*BatchModerateResponse, error) {
	var out BatchModerateResponse
	pattern := "/api/v1/moderate/batch"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationModerationServiceBatchModerate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ModerateComment ModerateComment checks a comment for harmful content.
func (c *ModerationServiceHTTPClientImpl) ModerateComment(ctx context.Context, in *ModerateCommentRequest, opts ...http.CallOption) (*ModerationResponse, error) {
	var out ModerationResponse
	pattern := "/api/v1/moderate/comment"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationModerationServiceModerateComment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ModeratePost ModeratePost checks a post for harmful content.
func (c *ModerationServiceHTTPClientImpl) ModeratePost(ctx context.Context, in *ModeratePostRequest, opts ...http.CallOption) (*ModerationResponse, error) {
	var out ModerationResponse
	pattern := "/api/v1/moderate/post"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationModerationServiceModeratePost))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationAdminServiceAddBadWord = "/moderation.v1.AdminService/AddBadWord"
const OperationAdminServiceListBadWords = "/moderation.v1.AdminService/ListBadWords"
const OperationAdminServiceRebuildBloomFilter = "/moderation.v1.AdminService/RebuildBloomFilter"
const OperationAdminServiceRemoveBadWord = "/moderation.v1.AdminService/RemoveBadWord"

type AdminServiceHTTPServer interface {
	// AddBadWord AddBadWord adds a word to the blocklist.
	AddBadWord(context.Context, *AddBadWordRequest) (*AddBadWordResponse, error)
	// ListBadWords ListBadWords lists all bad words.
	ListBadWords(context.Context, *ListBadWordsRequest) (*ListBadWordsResponse, error)
	// RebuildBloomFilter RebuildBloomFilter rebuilds the bloom filter.
	RebuildBloomFilter(context.Context, *RebuildBloomFilterRequest) (*RebuildBloomFilterResponse, error)
	// RemoveBadWord RemoveBadWord removes a word from the blocklist.
	RemoveBadWord(context.Context, *RemoveBadWordRequest) (*RemoveBadWordResponse, error)
}

func RegisterAdminServiceHTTPServer(s *http.Server, srv AdminServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/admin/badwords", _AdminService_AddBadWord0_HTTP_Handler(srv))
	r.DELETE("/api/v1/admin/badwords/{word}", _AdminService_RemoveBadWord0_HTTP_Handler(srv))
	r.GET("/api/v1/admin/badwords", _AdminService_ListBadWords0_HTTP_Handler(srv))
	r.POST("/api/v1/admin/bloom/rebuild", _AdminService_RebuildBloomFilter0_HTTP_Handler(srv))
}

func _AdminService_AddBadWord0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddBadWordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceAddBadWord)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddBadWord(ctx, req.(*AddBadWordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddBadWordResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_RemoveBadWord0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveBadWordRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceRemoveBadWord)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveBadWord(ctx, req.(*RemoveBadWordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveBadWordResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListBadWords0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBadWordsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListBadWords)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBadWords(ctx, req.(*ListBadWordsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBadWordsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_RebuildBloomFilter0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RebuildBloomFilterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceRebuildBloomFilter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RebuildBloomFilter(ctx, req.(*RebuildBloomFilterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RebuildBloomFilterResponse)
		return ctx.Result(200, reply)
	}
}

type AdminServiceHTTPClient interface {
	// AddBadWord AddBadWord adds a word to the blocklist.
	AddBadWord(ctx context.Context, req *AddBadWordRequest, opts ...http.CallOption) (rsp *AddBadWordResponse, err error)
	// ListBadWords ListBadWords lists all bad words.
	ListBadWords(ctx context.Context, req *ListBadWordsRequest, opts ...http.CallOption) (rsp *ListBadWordsResponse, err error)
	// RebuildBloomFilter RebuildBloomFilter rebuilds the bloom filter.
	RebuildBloomFilter(ctx context.Context, req *RebuildBloomFilterRequest, opts ...http.CallOption) (rsp *RebuildBloomFilterResponse, err error)
	// RemoveBadWord RemoveBadWord removes a word from the blocklist.
	RemoveBadWord(ctx context.Context, req *RemoveBadWordRequest, opts ...http.CallOption) (rsp *RemoveBadWordResponse, err error)
}

type AdminServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminServiceHTTPClient(client *http.Client) AdminServiceHTTPClient {
	return &AdminServiceHTTPClientImpl{client}
}

// AddBadWord AddBadWord adds a word to the blocklist.
func (c *AdminServiceHTTPClientImpl) AddBadWord(ctx context.Context, in *AddBadWordRequest, opts ...http.CallOption) (*AddBadWordResponse, error) {
	var out AddBadWordResponse
	pattern := "/api/v1/admin/badwords"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceAddBadWord))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListBadWords ListBadWords lists all bad words.
func (c *AdminServiceHTTPClientImpl) ListBadWords(ctx context.Context, in *ListBadWordsRequest, opts ...http.CallOption) (*ListBadWordsResponse, error) {
	var out ListBadWordsResponse
	pattern := "/api/v1/admin/badwords"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceListBadWords))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RebuildBloomFilter RebuildBloomFilter rebuilds the bloom filter.
func (c *AdminServiceHTTPClientImpl) RebuildBloomFilter(ctx context.Context, in *RebuildBloomFilterRequest, opts ...http.CallOption) (*RebuildBloomFilterResponse, error) {
	var out RebuildBloomFilterResponse
	pattern := "/api/v1/admin/bloom/rebuild"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceRebuildBloomFilter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveBadWord RemoveBadWord removes a word from the blocklist.
func (c *AdminServiceHTTPClientImpl) RemoveBadWord(ctx context.Context, in *RemoveBadWordRequest, opts ...http.CallOption) (*RemoveBadWordResponse, error) {
	var out RemoveBadWordResponse
	pattern := "/api/v1/admin/badwords/{word}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceRemoveBadWord))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
