// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: moderation/v1/moderation.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModerationService_ModeratePost_FullMethodName    = "/moderation.v1.ModerationService/ModeratePost"
	ModerationService_ModerateComment_FullMethodName = "/moderation.v1.ModerationService/ModerateComment"
	ModerationService_BatchModerate_FullMethodName   = "/moderation.v1.ModerationService/BatchModerate"
)

// ModerationServiceClient is the client API for ModerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModerationService provides content moderation for posts and comments.
type ModerationServiceClient interface {
	// ModeratePost checks a post for harmful content.
	ModeratePost(ctx context.Context, in *ModeratePostRequest, opts ...grpc.CallOption) (*ModerationResponse, error)
	// ModerateComment checks a comment for harmful content.
	ModerateComment(ctx context.Context, in *ModerateCommentRequest, opts ...grpc.CallOption) (*ModerationResponse, error)
	// BatchModerate checks multiple items at once.
	BatchModerate(ctx context.Context, in *BatchModerateRequest, opts ...grpc.CallOption) (*BatchModerateResponse, error)
}

type moderationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModerationServiceClient(cc grpc.ClientConnInterface) ModerationServiceClient {
	return &moderationServiceClient{cc}
}

func (c *moderationServiceClient) ModeratePost(ctx context.Context, in *ModeratePostRequest, opts ...grpc.CallOption) (*ModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModerationResponse)
	err := c.cc.Invoke(ctx, ModerationService_ModeratePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ModerateComment(ctx context.Context, in *ModerateCommentRequest, opts ...grpc.CallOption) (*ModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModerationResponse)
	err := c.cc.Invoke(ctx, ModerationService_ModerateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) BatchModerate(ctx context.Context, in *BatchModerateRequest, opts ...grpc.CallOption) (*BatchModerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchModerateResponse)
	err := c.cc.Invoke(ctx, ModerationService_BatchModerate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModerationServiceServer is the server API for ModerationService service.
// All implementations must embed UnimplementedModerationServiceServer
// for forward compatibility.
//
// ModerationService provides content moderation for posts and comments.
type ModerationServiceServer interface {
	// ModeratePost checks a post for harmful content.
	ModeratePost(context.Context, *ModeratePostRequest) (*ModerationResponse, error)
	// ModerateComment checks a comment for harmful content.
	ModerateComment(context.Context, *ModerateCommentRequest) (*ModerationResponse, error)
	// BatchModerate checks multiple items at once.
	BatchModerate(context.Context, *BatchModerateRequest) (*BatchModerateResponse, error)
	mustEmbedUnimplementedModerationServiceServer()
}

// UnimplementedModerationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModerationServiceServer struct{}

func (UnimplementedModerationServiceServer) ModeratePost(context.Context, *ModeratePostRequest) (*ModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModeratePost not implemented")
}
func (UnimplementedModerationServiceServer) ModerateComment(context.Context, *ModerateCommentRequest) (*ModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModerateComment not implemented")
}
func (UnimplementedModerationServiceServer) BatchModerate(context.Context, *BatchModerateRequest) (*BatchModerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchModerate not implemented")
}
func (UnimplementedModerationServiceServer) mustEmbedUnimplementedModerationServiceServer() {}
func (UnimplementedModerationServiceServer) testEmbeddedByValue()                           {}

// UnsafeModerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModerationServiceServer will
// result in compilation errors.
type UnsafeModerationServiceServer interface {
	mustEmbedUnimplementedModerationServiceServer()
}

func RegisterModerationServiceServer(s grpc.ServiceRegistrar, srv ModerationServiceServer) {
	// If the following call panics, it indicates UnimplementedModerationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModerationService_ServiceDesc, srv)
}

func _ModerationService_ModeratePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeratePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ModeratePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ModeratePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ModeratePost(ctx, req.(*ModeratePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ModerateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModerateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ModerateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ModerateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ModerateComment(ctx, req.(*ModerateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_BatchModerate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchModerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).BatchModerate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_BatchModerate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).BatchModerate(ctx, req.(*BatchModerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModerationService_ServiceDesc is the grpc.ServiceDesc for ModerationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModerationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moderation.v1.ModerationService",
	HandlerType: (*ModerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModeratePost",
			Handler:    _ModerationService_ModeratePost_Handler,
		},
		{
			MethodName: "ModerateComment",
			Handler:    _ModerationService_ModerateComment_Handler,
		},
		{
			MethodName: "BatchModerate",
			Handler:    _ModerationService_BatchModerate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moderation/v1/moderation.proto",
}

const (
	AdminService_AddBadWord_FullMethodName         = "/moderation.v1.AdminService/AddBadWord"
	AdminService_RemoveBadWord_FullMethodName      = "/moderation.v1.AdminService/RemoveBadWord"
	AdminService_ListBadWords_FullMethodName       = "/moderation.v1.AdminService/ListBadWords"
	AdminService_RebuildBloomFilter_FullMethodName = "/moderation.v1.AdminService/RebuildBloomFilter"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService provides admin operations for moderation.
type AdminServiceClient interface {
	// AddBadWord adds a word to the blocklist.
	AddBadWord(ctx context.Context, in *AddBadWordRequest, opts ...grpc.CallOption) (*AddBadWordResponse, error)
	// RemoveBadWord removes a word from the blocklist.
	RemoveBadWord(ctx context.Context, in *RemoveBadWordRequest, opts ...grpc.CallOption) (*RemoveBadWordResponse, error)
	// ListBadWords lists all bad words.
	ListBadWords(ctx context.Context, in *ListBadWordsRequest, opts ...grpc.CallOption) (*ListBadWordsResponse, error)
	// RebuildBloomFilter rebuilds the bloom filter.
	RebuildBloomFilter(ctx context.Context, in *RebuildBloomFilterRequest, opts ...grpc.CallOption) (*RebuildBloomFilterResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) AddBadWord(ctx context.Context, in *AddBadWordRequest, opts ...grpc.CallOption) (*AddBadWordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBadWordResponse)
	err := c.cc.Invoke(ctx, AdminService_AddBadWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RemoveBadWord(ctx context.Context, in *RemoveBadWordRequest, opts ...grpc.CallOption) (*RemoveBadWordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBadWordResponse)
	err := c.cc.Invoke(ctx, AdminService_RemoveBadWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListBadWords(ctx context.Context, in *ListBadWordsRequest, opts ...grpc.CallOption) (*ListBadWordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBadWordsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListBadWords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RebuildBloomFilter(ctx context.Context, in *RebuildBloomFilterRequest, opts ...grpc.CallOption) (*RebuildBloomFilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebuildBloomFilterResponse)
	err := c.cc.Invoke(ctx, AdminService_RebuildBloomFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService provides admin operations for moderation.
type AdminServiceServer interface {
	// AddBadWord adds a word to the blocklist.
	AddBadWord(context.Context, *AddBadWordRequest) (*AddBadWordResponse, error)
	// RemoveBadWord removes a word from the blocklist.
	RemoveBadWord(context.Context, *RemoveBadWordRequest) (*RemoveBadWordResponse, error)
	// ListBadWords lists all bad words.
	ListBadWords(context.Context, *ListBadWordsRequest) (*ListBadWordsResponse, error)
	// RebuildBloomFilter rebuilds the bloom filter.
	RebuildBloomFilter(context.Context, *RebuildBloomFilterRequest) (*RebuildBloomFilterResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) AddBadWord(context.Context, *AddBadWordRequest) (*AddBadWordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBadWord not implemented")
}
func (UnimplementedAdminServiceServer) RemoveBadWord(context.Context, *RemoveBadWordRequest) (*RemoveBadWordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBadWord not implemented")
}
func (UnimplementedAdminServiceServer) ListBadWords(context.Context, *ListBadWordsRequest) (*ListBadWordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBadWords not implemented")
}
func (UnimplementedAdminServiceServer) RebuildBloomFilter(context.Context, *RebuildBloomFilterRequest) (*RebuildBloomFilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebuildBloomFilter not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_AddBadWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBadWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AddBadWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AddBadWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AddBadWord(ctx, req.(*AddBadWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RemoveBadWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBadWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RemoveBadWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RemoveBadWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RemoveBadWord(ctx, req.(*RemoveBadWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListBadWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBadWordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListBadWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListBadWords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListBadWords(ctx, req.(*ListBadWordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RebuildBloomFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildBloomFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RebuildBloomFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RebuildBloomFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RebuildBloomFilter(ctx, req.(*RebuildBloomFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moderation.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBadWord",
			Handler:    _AdminService_AddBadWord_Handler,
		},
		{
			MethodName: "RemoveBadWord",
			Handler:    _AdminService_RemoveBadWord_Handler,
		},
		{
			MethodName: "ListBadWords",
			Handler:    _AdminService_ListBadWords_Handler,
		},
		{
			MethodName: "RebuildBloomFilter",
			Handler:    _AdminService_RebuildBloomFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moderation/v1/moderation.proto",
}
