# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import nsfw_image_pb2 as proto_dot_nsfw__image__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/nsfw_image_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NSFWImageDetectorStub(object):
    """NSFWImageDetector service for detecting NSFW content in images.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/nsfw.v1.NSFWImageDetector/Predict',
                request_serializer=proto_dot_nsfw__image__pb2.PredictRequest.SerializeToString,
                response_deserializer=proto_dot_nsfw__image__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.PredictFromURL = channel.unary_unary(
                '/nsfw.v1.NSFWImageDetector/PredictFromURL',
                request_serializer=proto_dot_nsfw__image__pb2.PredictURLRequest.SerializeToString,
                response_deserializer=proto_dot_nsfw__image__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.PredictBatchFromURLs = channel.unary_unary(
                '/nsfw.v1.NSFWImageDetector/PredictBatchFromURLs',
                request_serializer=proto_dot_nsfw__image__pb2.PredictBatchURLRequest.SerializeToString,
                response_deserializer=proto_dot_nsfw__image__pb2.PredictBatchResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/nsfw.v1.NSFWImageDetector/HealthCheck',
                request_serializer=proto_dot_nsfw__image__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_nsfw__image__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class NSFWImageDetectorServicer(object):
    """NSFWImageDetector service for detecting NSFW content in images.
    """

    def Predict(self, request, context):
        """Predict NSFW content from raw image bytes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictFromURL(self, request, context):
        """Predict NSFW content from a public image URL.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictBatchFromURLs(self, request, context):
        """Predict NSFW content for a batch of images (by URL).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NSFWImageDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=proto_dot_nsfw__image__pb2.PredictRequest.FromString,
                    response_serializer=proto_dot_nsfw__image__pb2.PredictResponse.SerializeToString,
            ),
            'PredictFromURL': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictFromURL,
                    request_deserializer=proto_dot_nsfw__image__pb2.PredictURLRequest.FromString,
                    response_serializer=proto_dot_nsfw__image__pb2.PredictResponse.SerializeToString,
            ),
            'PredictBatchFromURLs': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBatchFromURLs,
                    request_deserializer=proto_dot_nsfw__image__pb2.PredictBatchURLRequest.FromString,
                    response_serializer=proto_dot_nsfw__image__pb2.PredictBatchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_nsfw__image__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_nsfw__image__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nsfw.v1.NSFWImageDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nsfw.v1.NSFWImageDetector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NSFWImageDetector(object):
    """NSFWImageDetector service for detecting NSFW content in images.
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nsfw.v1.NSFWImageDetector/Predict',
            proto_dot_nsfw__image__pb2.PredictRequest.SerializeToString,
            proto_dot_nsfw__image__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictFromURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nsfw.v1.NSFWImageDetector/PredictFromURL',
            proto_dot_nsfw__image__pb2.PredictURLRequest.SerializeToString,
            proto_dot_nsfw__image__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictBatchFromURLs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nsfw.v1.NSFWImageDetector/PredictBatchFromURLs',
            proto_dot_nsfw__image__pb2.PredictBatchURLRequest.SerializeToString,
            proto_dot_nsfw__image__pb2.PredictBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nsfw.v1.NSFWImageDetector/HealthCheck',
            proto_dot_nsfw__image__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_nsfw__image__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
