// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: storage/v1/file.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_CreateFile_FullMethodName             = "/storage.v1.FileService/CreateFile"
	FileService_GetFile_FullMethodName                = "/storage.v1.FileService/GetFile"
	FileService_GetFilesByIDs_FullMethodName          = "/storage.v1.FileService/GetFilesByIDs"
	FileService_ListFiles_FullMethodName              = "/storage.v1.FileService/ListFiles"
	FileService_GetFileByHash_FullMethodName          = "/storage.v1.FileService/GetFileByHash"
	FileService_MoveFiles_FullMethodName              = "/storage.v1.FileService/MoveFiles"
	FileService_RenameFile_FullMethodName             = "/storage.v1.FileService/RenameFile"
	FileService_UpdateFavorite_FullMethodName         = "/storage.v1.FileService/UpdateFavorite"
	FileService_UpdateRecentAccess_FullMethodName     = "/storage.v1.FileService/UpdateRecentAccess"
	FileService_TrashFiles_FullMethodName             = "/storage.v1.FileService/TrashFiles"
	FileService_ListTrash_FullMethodName              = "/storage.v1.FileService/ListTrash"
	FileService_RestoreFiles_FullMethodName           = "/storage.v1.FileService/RestoreFiles"
	FileService_DeleteFilesPermanently_FullMethodName = "/storage.v1.FileService/DeleteFilesPermanently"
	FileService_EmptyTrash_FullMethodName             = "/storage.v1.FileService/EmptyTrash"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	// Create a new file
	CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error)
	// Get file by ID
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	// Get files by IDs
	GetFilesByIDs(ctx context.Context, in *GetFilesByIDsRequest, opts ...grpc.CallOption) (*GetFilesByIDsResponse, error)
	// List files in folder (with cursor pagination)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	// Get file by hash (for deduplication)
	GetFileByHash(ctx context.Context, in *GetFileByHashRequest, opts ...grpc.CallOption) (*GetFileByHashResponse, error)
	// Move files to folder
	MoveFiles(ctx context.Context, in *MoveFilesRequest, opts ...grpc.CallOption) (*MoveFilesResponse, error)
	// Rename file
	RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error)
	// Update favorite status
	UpdateFavorite(ctx context.Context, in *UpdateFavoriteRequest, opts ...grpc.CallOption) (*UpdateFavoriteResponse, error)
	// Update recent accessed time
	UpdateRecentAccess(ctx context.Context, in *UpdateRecentAccessRequest, opts ...grpc.CallOption) (*UpdateRecentAccessResponse, error)
	// Move files to trash (soft delete)
	TrashFiles(ctx context.Context, in *TrashFilesRequest, opts ...grpc.CallOption) (*TrashFilesResponse, error)
	// List files in trash
	ListTrash(ctx context.Context, in *ListTrashRequest, opts ...grpc.CallOption) (*ListTrashResponse, error)
	// Restore files from trash
	RestoreFiles(ctx context.Context, in *RestoreFilesRequest, opts ...grpc.CallOption) (*RestoreFilesResponse, error)
	// Delete files permanently
	DeleteFilesPermanently(ctx context.Context, in *DeleteFilesPermanentlyRequest, opts ...grpc.CallOption) (*DeleteFilesPermanentlyResponse, error)
	// Empty trash
	EmptyTrash(ctx context.Context, in *EmptyTrashRequest, opts ...grpc.CallOption) (*EmptyTrashResponse, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileResponse)
	err := c.cc.Invoke(ctx, FileService_CreateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, FileService_GetFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFilesByIDs(ctx context.Context, in *GetFilesByIDsRequest, opts ...grpc.CallOption) (*GetFilesByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFilesByIDsResponse)
	err := c.cc.Invoke(ctx, FileService_GetFilesByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, FileService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileByHash(ctx context.Context, in *GetFileByHashRequest, opts ...grpc.CallOption) (*GetFileByHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileByHashResponse)
	err := c.cc.Invoke(ctx, FileService_GetFileByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) MoveFiles(ctx context.Context, in *MoveFilesRequest, opts ...grpc.CallOption) (*MoveFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveFilesResponse)
	err := c.cc.Invoke(ctx, FileService_MoveFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameFileResponse)
	err := c.cc.Invoke(ctx, FileService_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UpdateFavorite(ctx context.Context, in *UpdateFavoriteRequest, opts ...grpc.CallOption) (*UpdateFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFavoriteResponse)
	err := c.cc.Invoke(ctx, FileService_UpdateFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UpdateRecentAccess(ctx context.Context, in *UpdateRecentAccessRequest, opts ...grpc.CallOption) (*UpdateRecentAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRecentAccessResponse)
	err := c.cc.Invoke(ctx, FileService_UpdateRecentAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) TrashFiles(ctx context.Context, in *TrashFilesRequest, opts ...grpc.CallOption) (*TrashFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrashFilesResponse)
	err := c.cc.Invoke(ctx, FileService_TrashFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ListTrash(ctx context.Context, in *ListTrashRequest, opts ...grpc.CallOption) (*ListTrashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrashResponse)
	err := c.cc.Invoke(ctx, FileService_ListTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) RestoreFiles(ctx context.Context, in *RestoreFilesRequest, opts ...grpc.CallOption) (*RestoreFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreFilesResponse)
	err := c.cc.Invoke(ctx, FileService_RestoreFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteFilesPermanently(ctx context.Context, in *DeleteFilesPermanentlyRequest, opts ...grpc.CallOption) (*DeleteFilesPermanentlyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFilesPermanentlyResponse)
	err := c.cc.Invoke(ctx, FileService_DeleteFilesPermanently_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) EmptyTrash(ctx context.Context, in *EmptyTrashRequest, opts ...grpc.CallOption) (*EmptyTrashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyTrashResponse)
	err := c.cc.Invoke(ctx, FileService_EmptyTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
type FileServiceServer interface {
	// Create a new file
	CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error)
	// Get file by ID
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	// Get files by IDs
	GetFilesByIDs(context.Context, *GetFilesByIDsRequest) (*GetFilesByIDsResponse, error)
	// List files in folder (with cursor pagination)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	// Get file by hash (for deduplication)
	GetFileByHash(context.Context, *GetFileByHashRequest) (*GetFileByHashResponse, error)
	// Move files to folder
	MoveFiles(context.Context, *MoveFilesRequest) (*MoveFilesResponse, error)
	// Rename file
	RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error)
	// Update favorite status
	UpdateFavorite(context.Context, *UpdateFavoriteRequest) (*UpdateFavoriteResponse, error)
	// Update recent accessed time
	UpdateRecentAccess(context.Context, *UpdateRecentAccessRequest) (*UpdateRecentAccessResponse, error)
	// Move files to trash (soft delete)
	TrashFiles(context.Context, *TrashFilesRequest) (*TrashFilesResponse, error)
	// List files in trash
	ListTrash(context.Context, *ListTrashRequest) (*ListTrashResponse, error)
	// Restore files from trash
	RestoreFiles(context.Context, *RestoreFilesRequest) (*RestoreFilesResponse, error)
	// Delete files permanently
	DeleteFilesPermanently(context.Context, *DeleteFilesPermanentlyRequest) (*DeleteFilesPermanentlyResponse, error)
	// Empty trash
	EmptyTrash(context.Context, *EmptyTrashRequest) (*EmptyTrashResponse, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFile not implemented")
}
func (UnimplementedFileServiceServer) GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedFileServiceServer) GetFilesByIDs(context.Context, *GetFilesByIDsRequest) (*GetFilesByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFilesByIDs not implemented")
}
func (UnimplementedFileServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedFileServiceServer) GetFileByHash(context.Context, *GetFileByHashRequest) (*GetFileByHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileByHash not implemented")
}
func (UnimplementedFileServiceServer) MoveFiles(context.Context, *MoveFilesRequest) (*MoveFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveFiles not implemented")
}
func (UnimplementedFileServiceServer) RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedFileServiceServer) UpdateFavorite(context.Context, *UpdateFavoriteRequest) (*UpdateFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFavorite not implemented")
}
func (UnimplementedFileServiceServer) UpdateRecentAccess(context.Context, *UpdateRecentAccessRequest) (*UpdateRecentAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRecentAccess not implemented")
}
func (UnimplementedFileServiceServer) TrashFiles(context.Context, *TrashFilesRequest) (*TrashFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrashFiles not implemented")
}
func (UnimplementedFileServiceServer) ListTrash(context.Context, *ListTrashRequest) (*ListTrashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrash not implemented")
}
func (UnimplementedFileServiceServer) RestoreFiles(context.Context, *RestoreFilesRequest) (*RestoreFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreFiles not implemented")
}
func (UnimplementedFileServiceServer) DeleteFilesPermanently(context.Context, *DeleteFilesPermanentlyRequest) (*DeleteFilesPermanentlyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFilesPermanently not implemented")
}
func (UnimplementedFileServiceServer) EmptyTrash(context.Context, *EmptyTrashRequest) (*EmptyTrashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmptyTrash not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call panics, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CreateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CreateFile(ctx, req.(*CreateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFilesByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFilesByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFilesByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFilesByIDs(ctx, req.(*GetFilesByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFileByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileByHash(ctx, req.(*GetFileByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_MoveFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).MoveFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_MoveFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).MoveFiles(ctx, req.(*MoveFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).RenameFile(ctx, req.(*RenameFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UpdateFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UpdateFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UpdateFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UpdateFavorite(ctx, req.(*UpdateFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UpdateRecentAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecentAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UpdateRecentAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_UpdateRecentAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UpdateRecentAccess(ctx, req.(*UpdateRecentAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_TrashFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrashFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).TrashFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_TrashFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).TrashFiles(ctx, req.(*TrashFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ListTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ListTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ListTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ListTrash(ctx, req.(*ListTrashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_RestoreFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).RestoreFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_RestoreFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).RestoreFiles(ctx, req.(*RestoreFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteFilesPermanently_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFilesPermanentlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteFilesPermanently(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DeleteFilesPermanently_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteFilesPermanently(ctx, req.(*DeleteFilesPermanentlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_EmptyTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyTrashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).EmptyTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_EmptyTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).EmptyTrash(ctx, req.(*EmptyTrashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.v1.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFile",
			Handler:    _FileService_CreateFile_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _FileService_GetFile_Handler,
		},
		{
			MethodName: "GetFilesByIDs",
			Handler:    _FileService_GetFilesByIDs_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _FileService_ListFiles_Handler,
		},
		{
			MethodName: "GetFileByHash",
			Handler:    _FileService_GetFileByHash_Handler,
		},
		{
			MethodName: "MoveFiles",
			Handler:    _FileService_MoveFiles_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _FileService_RenameFile_Handler,
		},
		{
			MethodName: "UpdateFavorite",
			Handler:    _FileService_UpdateFavorite_Handler,
		},
		{
			MethodName: "UpdateRecentAccess",
			Handler:    _FileService_UpdateRecentAccess_Handler,
		},
		{
			MethodName: "TrashFiles",
			Handler:    _FileService_TrashFiles_Handler,
		},
		{
			MethodName: "ListTrash",
			Handler:    _FileService_ListTrash_Handler,
		},
		{
			MethodName: "RestoreFiles",
			Handler:    _FileService_RestoreFiles_Handler,
		},
		{
			MethodName: "DeleteFilesPermanently",
			Handler:    _FileService_DeleteFilesPermanently_Handler,
		},
		{
			MethodName: "EmptyTrash",
			Handler:    _FileService_EmptyTrash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/v1/file.proto",
}
