// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.4
// source: storage/v1/plan.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPlanServiceCreatePlan = "/storage.v1.PlanService/CreatePlan"
const OperationPlanServiceDeletePlan = "/storage.v1.PlanService/DeletePlan"
const OperationPlanServiceGetPlan = "/storage.v1.PlanService/GetPlan"
const OperationPlanServiceListPlans = "/storage.v1.PlanService/ListPlans"
const OperationPlanServiceUpdatePlan = "/storage.v1.PlanService/UpdatePlan"

type PlanServiceHTTPServer interface {
	// CreatePlan Create a new plan
	CreatePlan(context.Context, *CreatePlanRequest) (*CreatePlanResponse, error)
	// DeletePlan Delete plan
	DeletePlan(context.Context, *DeletePlanRequest) (*DeletePlanResponse, error)
	// GetPlan Get plan by ID
	GetPlan(context.Context, *GetPlanRequest) (*GetPlanResponse, error)
	// ListPlans List all plans
	ListPlans(context.Context, *ListPlansRequest) (*ListPlansResponse, error)
	// UpdatePlan Update plan
	UpdatePlan(context.Context, *UpdatePlanRequest) (*UpdatePlanResponse, error)
}

func RegisterPlanServiceHTTPServer(s *http.Server, srv PlanServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/plans", _PlanService_CreatePlan0_HTTP_Handler(srv))
	r.GET("/v1/plans/{id}", _PlanService_GetPlan0_HTTP_Handler(srv))
	r.GET("/v1/plans", _PlanService_ListPlans0_HTTP_Handler(srv))
	r.PATCH("/v1/plans/{id}", _PlanService_UpdatePlan0_HTTP_Handler(srv))
	r.DELETE("/v1/plans/{id}", _PlanService_DeletePlan0_HTTP_Handler(srv))
}

func _PlanService_CreatePlan0_HTTP_Handler(srv PlanServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlanServiceCreatePlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePlan(ctx, req.(*CreatePlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePlanResponse)
		return ctx.Result(200, reply)
	}
}

func _PlanService_GetPlan0_HTTP_Handler(srv PlanServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPlanRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlanServiceGetPlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPlan(ctx, req.(*GetPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPlanResponse)
		return ctx.Result(200, reply)
	}
}

func _PlanService_ListPlans0_HTTP_Handler(srv PlanServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPlansRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlanServiceListPlans)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPlans(ctx, req.(*ListPlansRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPlansResponse)
		return ctx.Result(200, reply)
	}
}

func _PlanService_UpdatePlan0_HTTP_Handler(srv PlanServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlanServiceUpdatePlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePlan(ctx, req.(*UpdatePlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePlanResponse)
		return ctx.Result(200, reply)
	}
}

func _PlanService_DeletePlan0_HTTP_Handler(srv PlanServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePlanRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlanServiceDeletePlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePlan(ctx, req.(*DeletePlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeletePlanResponse)
		return ctx.Result(200, reply)
	}
}

type PlanServiceHTTPClient interface {
	// CreatePlan Create a new plan
	CreatePlan(ctx context.Context, req *CreatePlanRequest, opts ...http.CallOption) (rsp *CreatePlanResponse, err error)
	// DeletePlan Delete plan
	DeletePlan(ctx context.Context, req *DeletePlanRequest, opts ...http.CallOption) (rsp *DeletePlanResponse, err error)
	// GetPlan Get plan by ID
	GetPlan(ctx context.Context, req *GetPlanRequest, opts ...http.CallOption) (rsp *GetPlanResponse, err error)
	// ListPlans List all plans
	ListPlans(ctx context.Context, req *ListPlansRequest, opts ...http.CallOption) (rsp *ListPlansResponse, err error)
	// UpdatePlan Update plan
	UpdatePlan(ctx context.Context, req *UpdatePlanRequest, opts ...http.CallOption) (rsp *UpdatePlanResponse, err error)
}

type PlanServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPlanServiceHTTPClient(client *http.Client) PlanServiceHTTPClient {
	return &PlanServiceHTTPClientImpl{client}
}

// CreatePlan Create a new plan
func (c *PlanServiceHTTPClientImpl) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...http.CallOption) (*CreatePlanResponse, error) {
	var out CreatePlanResponse
	pattern := "/v1/plans"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlanServiceCreatePlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeletePlan Delete plan
func (c *PlanServiceHTTPClientImpl) DeletePlan(ctx context.Context, in *DeletePlanRequest, opts ...http.CallOption) (*DeletePlanResponse, error) {
	var out DeletePlanResponse
	pattern := "/v1/plans/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlanServiceDeletePlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPlan Get plan by ID
func (c *PlanServiceHTTPClientImpl) GetPlan(ctx context.Context, in *GetPlanRequest, opts ...http.CallOption) (*GetPlanResponse, error) {
	var out GetPlanResponse
	pattern := "/v1/plans/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlanServiceGetPlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPlans List all plans
func (c *PlanServiceHTTPClientImpl) ListPlans(ctx context.Context, in *ListPlansRequest, opts ...http.CallOption) (*ListPlansResponse, error) {
	var out ListPlansResponse
	pattern := "/v1/plans"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPlanServiceListPlans))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePlan Update plan
func (c *PlanServiceHTTPClientImpl) UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...http.CallOption) (*UpdatePlanResponse, error) {
	var out UpdatePlanResponse
	pattern := "/v1/plans/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlanServiceUpdatePlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
