// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: storage/v1/plan.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	v1 "storage/api/common/v1"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StorageQuota  int64                  `protobuf:"varint,3,opt,name=storage_quota,json=storageQuota,proto3" json:"storage_quota,omitempty"` // in bytes
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPrice int64                  `protobuf:"varint,5,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	DurationDays  int32                  `protobuf:"varint,6,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"` // 30, 365, 0 = lifetime
	Description   *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedBy     *string                `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_storage_v1_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_storage_v1_plan_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetStorageQuota() int64 {
	if x != nil {
		return x.StorageQuota
	}
	return 0
}

func (x *Plan) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Plan) GetDiscountPrice() int64 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *Plan) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *Plan) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Plan) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *Plan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Plan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreatePlan
type CreatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StorageQuota  int64                  `protobuf:"varint,2,opt,name=storage_quota,json=storageQuota,proto3" json:"storage_quota,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPrice int64                  `protobuf:"varint,4,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	DurationDays  int32                  `protobuf:"varint,5,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanRequest) Reset() {
	*x = CreatePlanRequest{}
	mi := &file_storage_v1_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanRequest) ProtoMessage() {}

func (x *CreatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanRequest.ProtoReflect.Descriptor instead.
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_plan_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlanRequest) GetStorageQuota() int64 {
	if x != nil {
		return x.StorageQuota
	}
	return 0
}

func (x *CreatePlanRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreatePlanRequest) GetDiscountPrice() int64 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *CreatePlanRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *CreatePlanRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreatePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanResponse) Reset() {
	*x = CreatePlanResponse{}
	mi := &file_storage_v1_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanResponse) ProtoMessage() {}

func (x *CreatePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanResponse.ProtoReflect.Descriptor instead.
func (*CreatePlanResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_plan_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePlanResponse) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

// GetPlan
type GetPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanRequest) Reset() {
	*x = GetPlanRequest{}
	mi := &file_storage_v1_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRequest) ProtoMessage() {}

func (x *GetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_plan_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanResponse) Reset() {
	*x = GetPlanResponse{}
	mi := &file_storage_v1_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanResponse) ProtoMessage() {}

func (x *GetPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanResponse.ProtoReflect.Descriptor instead.
func (*GetPlanResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_plan_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlanResponse) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

// ListPlans
type ListPlansRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Pagination    *v1.CursorPaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_storage_v1_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_plan_proto_rawDescGZIP(), []int{5}
}

func (x *ListPlansRequest) GetPagination() *v1.CursorPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPlansResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Plans         []*Plan                      `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	Pagination    *v1.CursorPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansResponse) Reset() {
	*x = ListPlansResponse{}
	mi := &file_storage_v1_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansResponse) ProtoMessage() {}

func (x *ListPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansResponse.ProtoReflect.Descriptor instead.
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_plan_proto_rawDescGZIP(), []int{6}
}

func (x *ListPlansResponse) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *ListPlansResponse) GetPagination() *v1.CursorPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// UpdatePlan
type UpdatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	StorageQuota  *int64                 `protobuf:"varint,3,opt,name=storage_quota,json=storageQuota,proto3,oneof" json:"storage_quota,omitempty"`
	Price         *int64                 `protobuf:"varint,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	DiscountPrice *int64                 `protobuf:"varint,5,opt,name=discount_price,json=discountPrice,proto3,oneof" json:"discount_price,omitempty"`
	DurationDays  *int32                 `protobuf:"varint,6,opt,name=duration_days,json=durationDays,proto3,oneof" json:"duration_days,omitempty"`
	Description   *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanRequest) Reset() {
	*x = UpdatePlanRequest{}
	mi := &file_storage_v1_plan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanRequest) ProtoMessage() {}

func (x *UpdatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_plan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_plan_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePlanRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdatePlanRequest) GetStorageQuota() int64 {
	if x != nil && x.StorageQuota != nil {
		return *x.StorageQuota
	}
	return 0
}

func (x *UpdatePlanRequest) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdatePlanRequest) GetDiscountPrice() int64 {
	if x != nil && x.DiscountPrice != nil {
		return *x.DiscountPrice
	}
	return 0
}

func (x *UpdatePlanRequest) GetDurationDays() int32 {
	if x != nil && x.DurationDays != nil {
		return *x.DurationDays
	}
	return 0
}

func (x *UpdatePlanRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdatePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanResponse) Reset() {
	*x = UpdatePlanResponse{}
	mi := &file_storage_v1_plan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanResponse) ProtoMessage() {}

func (x *UpdatePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_plan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlanResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_plan_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePlanResponse) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

// DeletePlan
type DeletePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanRequest) Reset() {
	*x = DeletePlanRequest{}
	mi := &file_storage_v1_plan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanRequest) ProtoMessage() {}

func (x *DeletePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_plan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanRequest.ProtoReflect.Descriptor instead.
func (*DeletePlanRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_plan_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlanResponse) Reset() {
	*x = DeletePlanResponse{}
	mi := &file_storage_v1_plan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlanResponse) ProtoMessage() {}

func (x *DeletePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_plan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlanResponse.ProtoReflect.Descriptor instead.
func (*DeletePlanResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_plan_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_storage_v1_plan_proto protoreflect.FileDescriptor

const file_storage_v1_plan_proto_rawDesc = "" +
	"\n" +
	"\x15storage/v1/plan.proto\x12\n" +
	"storage.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1acommon/v1/pagination.proto\"\x91\x03\n" +
	"\x04Plan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rstorage_quota\x18\x03 \x01(\x03R\fstorageQuota\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12%\n" +
	"\x0ediscount_price\x18\x05 \x01(\x03R\rdiscountPrice\x12#\n" +
	"\rduration_days\x18\x06 \x01(\x05R\fdurationDays\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x00R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\b \x01(\tH\x01R\tcreatedBy\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_created_by\"\xe5\x01\n" +
	"\x11CreatePlanRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rstorage_quota\x18\x02 \x01(\x03R\fstorageQuota\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12%\n" +
	"\x0ediscount_price\x18\x04 \x01(\x03R\rdiscountPrice\x12#\n" +
	"\rduration_days\x18\x05 \x01(\x05R\fdurationDays\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\":\n" +
	"\x12CreatePlanResponse\x12$\n" +
	"\x04plan\x18\x01 \x01(\v2\x10.storage.v1.PlanR\x04plan\" \n" +
	"\x0eGetPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x0fGetPlanResponse\x12$\n" +
	"\x04plan\x18\x01 \x01(\v2\x10.storage.v1.PlanR\x04plan\"V\n" +
	"\x10ListPlansRequest\x12B\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\".common.v1.CursorPaginationRequestR\n" +
	"pagination\"\x80\x01\n" +
	"\x11ListPlansResponse\x12&\n" +
	"\x05plans\x18\x01 \x03(\v2\x10.storage.v1.PlanR\x05plans\x12C\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2#.common.v1.CursorPaginationResponseR\n" +
	"pagination\"\xd8\x02\n" +
	"\x11UpdatePlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12(\n" +
	"\rstorage_quota\x18\x03 \x01(\x03H\x01R\fstorageQuota\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x04 \x01(\x03H\x02R\x05price\x88\x01\x01\x12*\n" +
	"\x0ediscount_price\x18\x05 \x01(\x03H\x03R\rdiscountPrice\x88\x01\x01\x12(\n" +
	"\rduration_days\x18\x06 \x01(\x05H\x04R\fdurationDays\x88\x01\x01\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x05R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\x10\n" +
	"\x0e_storage_quotaB\b\n" +
	"\x06_priceB\x11\n" +
	"\x0f_discount_priceB\x10\n" +
	"\x0e_duration_daysB\x0e\n" +
	"\f_description\":\n" +
	"\x12UpdatePlanResponse\x12$\n" +
	"\x04plan\x18\x01 \x01(\v2\x10.storage.v1.PlanR\x04plan\"#\n" +
	"\x11DeletePlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeletePlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf6\x03\n" +
	"\vPlanService\x12a\n" +
	"\n" +
	"CreatePlan\x12\x1d.storage.v1.CreatePlanRequest\x1a\x1e.storage.v1.CreatePlanResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/plans\x12Z\n" +
	"\aGetPlan\x12\x1a.storage.v1.GetPlanRequest\x1a\x1b.storage.v1.GetPlanResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/plans/{id}\x12[\n" +
	"\tListPlans\x12\x1c.storage.v1.ListPlansRequest\x1a\x1d.storage.v1.ListPlansResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/plans\x12f\n" +
	"\n" +
	"UpdatePlan\x12\x1d.storage.v1.UpdatePlanRequest\x1a\x1e.storage.v1.UpdatePlanResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*2\x0e/v1/plans/{id}\x12c\n" +
	"\n" +
	"DeletePlan\x12\x1d.storage.v1.DeletePlanRequest\x1a\x1e.storage.v1.DeletePlanResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/plans/{id}B\x1bZ\x19storage/api/storage/v1;v1b\x06proto3"

var (
	file_storage_v1_plan_proto_rawDescOnce sync.Once
	file_storage_v1_plan_proto_rawDescData []byte
)

func file_storage_v1_plan_proto_rawDescGZIP() []byte {
	file_storage_v1_plan_proto_rawDescOnce.Do(func() {
		file_storage_v1_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v1_plan_proto_rawDesc), len(file_storage_v1_plan_proto_rawDesc)))
	})
	return file_storage_v1_plan_proto_rawDescData
}

var file_storage_v1_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_storage_v1_plan_proto_goTypes = []any{
	(*Plan)(nil),                        // 0: storage.v1.Plan
	(*CreatePlanRequest)(nil),           // 1: storage.v1.CreatePlanRequest
	(*CreatePlanResponse)(nil),          // 2: storage.v1.CreatePlanResponse
	(*GetPlanRequest)(nil),              // 3: storage.v1.GetPlanRequest
	(*GetPlanResponse)(nil),             // 4: storage.v1.GetPlanResponse
	(*ListPlansRequest)(nil),            // 5: storage.v1.ListPlansRequest
	(*ListPlansResponse)(nil),           // 6: storage.v1.ListPlansResponse
	(*UpdatePlanRequest)(nil),           // 7: storage.v1.UpdatePlanRequest
	(*UpdatePlanResponse)(nil),          // 8: storage.v1.UpdatePlanResponse
	(*DeletePlanRequest)(nil),           // 9: storage.v1.DeletePlanRequest
	(*DeletePlanResponse)(nil),          // 10: storage.v1.DeletePlanResponse
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
	(*v1.CursorPaginationRequest)(nil),  // 12: common.v1.CursorPaginationRequest
	(*v1.CursorPaginationResponse)(nil), // 13: common.v1.CursorPaginationResponse
}
var file_storage_v1_plan_proto_depIdxs = []int32{
	11, // 0: storage.v1.Plan.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: storage.v1.Plan.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: storage.v1.CreatePlanResponse.plan:type_name -> storage.v1.Plan
	0,  // 3: storage.v1.GetPlanResponse.plan:type_name -> storage.v1.Plan
	12, // 4: storage.v1.ListPlansRequest.pagination:type_name -> common.v1.CursorPaginationRequest
	0,  // 5: storage.v1.ListPlansResponse.plans:type_name -> storage.v1.Plan
	13, // 6: storage.v1.ListPlansResponse.pagination:type_name -> common.v1.CursorPaginationResponse
	0,  // 7: storage.v1.UpdatePlanResponse.plan:type_name -> storage.v1.Plan
	1,  // 8: storage.v1.PlanService.CreatePlan:input_type -> storage.v1.CreatePlanRequest
	3,  // 9: storage.v1.PlanService.GetPlan:input_type -> storage.v1.GetPlanRequest
	5,  // 10: storage.v1.PlanService.ListPlans:input_type -> storage.v1.ListPlansRequest
	7,  // 11: storage.v1.PlanService.UpdatePlan:input_type -> storage.v1.UpdatePlanRequest
	9,  // 12: storage.v1.PlanService.DeletePlan:input_type -> storage.v1.DeletePlanRequest
	2,  // 13: storage.v1.PlanService.CreatePlan:output_type -> storage.v1.CreatePlanResponse
	4,  // 14: storage.v1.PlanService.GetPlan:output_type -> storage.v1.GetPlanResponse
	6,  // 15: storage.v1.PlanService.ListPlans:output_type -> storage.v1.ListPlansResponse
	8,  // 16: storage.v1.PlanService.UpdatePlan:output_type -> storage.v1.UpdatePlanResponse
	10, // 17: storage.v1.PlanService.DeletePlan:output_type -> storage.v1.DeletePlanResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_storage_v1_plan_proto_init() }
func file_storage_v1_plan_proto_init() {
	if File_storage_v1_plan_proto != nil {
		return
	}
	file_storage_v1_plan_proto_msgTypes[0].OneofWrappers = []any{}
	file_storage_v1_plan_proto_msgTypes[1].OneofWrappers = []any{}
	file_storage_v1_plan_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v1_plan_proto_rawDesc), len(file_storage_v1_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_v1_plan_proto_goTypes,
		DependencyIndexes: file_storage_v1_plan_proto_depIdxs,
		MessageInfos:      file_storage_v1_plan_proto_msgTypes,
	}.Build()
	File_storage_v1_plan_proto = out.File
	file_storage_v1_plan_proto_goTypes = nil
	file_storage_v1_plan_proto_depIdxs = nil
}
