// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: storage/v1/ps_file.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PsFileService_CreatePsFile_FullMethodName            = "/storage.v1.PsFileService/CreatePsFile"
	PsFileService_GetPsFile_FullMethodName               = "/storage.v1.PsFileService/GetPsFile"
	PsFileService_GetPsFileByHash_FullMethodName         = "/storage.v1.PsFileService/GetPsFileByHash"
	PsFileService_CheckPsFileExists_FullMethodName       = "/storage.v1.PsFileService/CheckPsFileExists"
	PsFileService_ListPsFiles_FullMethodName             = "/storage.v1.PsFileService/ListPsFiles"
	PsFileService_UpdatePsFileStatus_FullMethodName      = "/storage.v1.PsFileService/UpdatePsFileStatus"
	PsFileService_IncrementReferenceCount_FullMethodName = "/storage.v1.PsFileService/IncrementReferenceCount"
	PsFileService_DecrementReferenceCount_FullMethodName = "/storage.v1.PsFileService/DecrementReferenceCount"
)

// PsFileServiceClient is the client API for PsFileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PsFileServiceClient interface {
	// Create a new physical file record
	CreatePsFile(ctx context.Context, in *CreatePsFileRequest, opts ...grpc.CallOption) (*CreatePsFileResponse, error)
	// Get physical file by ID
	GetPsFile(ctx context.Context, in *GetPsFileRequest, opts ...grpc.CallOption) (*GetPsFileResponse, error)
	// Get physical file by hash (for deduplication)
	GetPsFileByHash(ctx context.Context, in *GetPsFileByHashRequest, opts ...grpc.CallOption) (*GetPsFileByHashResponse, error)
	// Check if physical file exists by hash
	CheckPsFileExists(ctx context.Context, in *CheckPsFileExistsRequest, opts ...grpc.CallOption) (*CheckPsFileExistsResponse, error)
	// List all physical files
	ListPsFiles(ctx context.Context, in *ListPsFilesRequest, opts ...grpc.CallOption) (*ListPsFilesResponse, error)
	// Update physical file status
	UpdatePsFileStatus(ctx context.Context, in *UpdatePsFileStatusRequest, opts ...grpc.CallOption) (*UpdatePsFileStatusResponse, error)
	// Increment reference count (when file is referenced by another user)
	IncrementReferenceCount(ctx context.Context, in *IncrementReferenceCountRequest, opts ...grpc.CallOption) (*IncrementReferenceCountResponse, error)
	// Decrement reference count (when file is deleted by a user)
	DecrementReferenceCount(ctx context.Context, in *DecrementReferenceCountRequest, opts ...grpc.CallOption) (*DecrementReferenceCountResponse, error)
}

type psFileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPsFileServiceClient(cc grpc.ClientConnInterface) PsFileServiceClient {
	return &psFileServiceClient{cc}
}

func (c *psFileServiceClient) CreatePsFile(ctx context.Context, in *CreatePsFileRequest, opts ...grpc.CallOption) (*CreatePsFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePsFileResponse)
	err := c.cc.Invoke(ctx, PsFileService_CreatePsFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *psFileServiceClient) GetPsFile(ctx context.Context, in *GetPsFileRequest, opts ...grpc.CallOption) (*GetPsFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPsFileResponse)
	err := c.cc.Invoke(ctx, PsFileService_GetPsFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *psFileServiceClient) GetPsFileByHash(ctx context.Context, in *GetPsFileByHashRequest, opts ...grpc.CallOption) (*GetPsFileByHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPsFileByHashResponse)
	err := c.cc.Invoke(ctx, PsFileService_GetPsFileByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *psFileServiceClient) CheckPsFileExists(ctx context.Context, in *CheckPsFileExistsRequest, opts ...grpc.CallOption) (*CheckPsFileExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPsFileExistsResponse)
	err := c.cc.Invoke(ctx, PsFileService_CheckPsFileExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *psFileServiceClient) ListPsFiles(ctx context.Context, in *ListPsFilesRequest, opts ...grpc.CallOption) (*ListPsFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPsFilesResponse)
	err := c.cc.Invoke(ctx, PsFileService_ListPsFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *psFileServiceClient) UpdatePsFileStatus(ctx context.Context, in *UpdatePsFileStatusRequest, opts ...grpc.CallOption) (*UpdatePsFileStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePsFileStatusResponse)
	err := c.cc.Invoke(ctx, PsFileService_UpdatePsFileStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *psFileServiceClient) IncrementReferenceCount(ctx context.Context, in *IncrementReferenceCountRequest, opts ...grpc.CallOption) (*IncrementReferenceCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementReferenceCountResponse)
	err := c.cc.Invoke(ctx, PsFileService_IncrementReferenceCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *psFileServiceClient) DecrementReferenceCount(ctx context.Context, in *DecrementReferenceCountRequest, opts ...grpc.CallOption) (*DecrementReferenceCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecrementReferenceCountResponse)
	err := c.cc.Invoke(ctx, PsFileService_DecrementReferenceCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PsFileServiceServer is the server API for PsFileService service.
// All implementations must embed UnimplementedPsFileServiceServer
// for forward compatibility.
type PsFileServiceServer interface {
	// Create a new physical file record
	CreatePsFile(context.Context, *CreatePsFileRequest) (*CreatePsFileResponse, error)
	// Get physical file by ID
	GetPsFile(context.Context, *GetPsFileRequest) (*GetPsFileResponse, error)
	// Get physical file by hash (for deduplication)
	GetPsFileByHash(context.Context, *GetPsFileByHashRequest) (*GetPsFileByHashResponse, error)
	// Check if physical file exists by hash
	CheckPsFileExists(context.Context, *CheckPsFileExistsRequest) (*CheckPsFileExistsResponse, error)
	// List all physical files
	ListPsFiles(context.Context, *ListPsFilesRequest) (*ListPsFilesResponse, error)
	// Update physical file status
	UpdatePsFileStatus(context.Context, *UpdatePsFileStatusRequest) (*UpdatePsFileStatusResponse, error)
	// Increment reference count (when file is referenced by another user)
	IncrementReferenceCount(context.Context, *IncrementReferenceCountRequest) (*IncrementReferenceCountResponse, error)
	// Decrement reference count (when file is deleted by a user)
	DecrementReferenceCount(context.Context, *DecrementReferenceCountRequest) (*DecrementReferenceCountResponse, error)
	mustEmbedUnimplementedPsFileServiceServer()
}

// UnimplementedPsFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPsFileServiceServer struct{}

func (UnimplementedPsFileServiceServer) CreatePsFile(context.Context, *CreatePsFileRequest) (*CreatePsFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePsFile not implemented")
}
func (UnimplementedPsFileServiceServer) GetPsFile(context.Context, *GetPsFileRequest) (*GetPsFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPsFile not implemented")
}
func (UnimplementedPsFileServiceServer) GetPsFileByHash(context.Context, *GetPsFileByHashRequest) (*GetPsFileByHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPsFileByHash not implemented")
}
func (UnimplementedPsFileServiceServer) CheckPsFileExists(context.Context, *CheckPsFileExistsRequest) (*CheckPsFileExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPsFileExists not implemented")
}
func (UnimplementedPsFileServiceServer) ListPsFiles(context.Context, *ListPsFilesRequest) (*ListPsFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPsFiles not implemented")
}
func (UnimplementedPsFileServiceServer) UpdatePsFileStatus(context.Context, *UpdatePsFileStatusRequest) (*UpdatePsFileStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePsFileStatus not implemented")
}
func (UnimplementedPsFileServiceServer) IncrementReferenceCount(context.Context, *IncrementReferenceCountRequest) (*IncrementReferenceCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementReferenceCount not implemented")
}
func (UnimplementedPsFileServiceServer) DecrementReferenceCount(context.Context, *DecrementReferenceCountRequest) (*DecrementReferenceCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecrementReferenceCount not implemented")
}
func (UnimplementedPsFileServiceServer) mustEmbedUnimplementedPsFileServiceServer() {}
func (UnimplementedPsFileServiceServer) testEmbeddedByValue()                       {}

// UnsafePsFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PsFileServiceServer will
// result in compilation errors.
type UnsafePsFileServiceServer interface {
	mustEmbedUnimplementedPsFileServiceServer()
}

func RegisterPsFileServiceServer(s grpc.ServiceRegistrar, srv PsFileServiceServer) {
	// If the following call panics, it indicates UnimplementedPsFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PsFileService_ServiceDesc, srv)
}

func _PsFileService_CreatePsFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePsFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsFileServiceServer).CreatePsFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PsFileService_CreatePsFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsFileServiceServer).CreatePsFile(ctx, req.(*CreatePsFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PsFileService_GetPsFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPsFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsFileServiceServer).GetPsFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PsFileService_GetPsFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsFileServiceServer).GetPsFile(ctx, req.(*GetPsFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PsFileService_GetPsFileByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPsFileByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsFileServiceServer).GetPsFileByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PsFileService_GetPsFileByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsFileServiceServer).GetPsFileByHash(ctx, req.(*GetPsFileByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PsFileService_CheckPsFileExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPsFileExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsFileServiceServer).CheckPsFileExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PsFileService_CheckPsFileExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsFileServiceServer).CheckPsFileExists(ctx, req.(*CheckPsFileExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PsFileService_ListPsFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPsFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsFileServiceServer).ListPsFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PsFileService_ListPsFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsFileServiceServer).ListPsFiles(ctx, req.(*ListPsFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PsFileService_UpdatePsFileStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePsFileStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsFileServiceServer).UpdatePsFileStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PsFileService_UpdatePsFileStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsFileServiceServer).UpdatePsFileStatus(ctx, req.(*UpdatePsFileStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PsFileService_IncrementReferenceCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementReferenceCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsFileServiceServer).IncrementReferenceCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PsFileService_IncrementReferenceCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsFileServiceServer).IncrementReferenceCount(ctx, req.(*IncrementReferenceCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PsFileService_DecrementReferenceCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrementReferenceCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsFileServiceServer).DecrementReferenceCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PsFileService_DecrementReferenceCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsFileServiceServer).DecrementReferenceCount(ctx, req.(*DecrementReferenceCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PsFileService_ServiceDesc is the grpc.ServiceDesc for PsFileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PsFileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.v1.PsFileService",
	HandlerType: (*PsFileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePsFile",
			Handler:    _PsFileService_CreatePsFile_Handler,
		},
		{
			MethodName: "GetPsFile",
			Handler:    _PsFileService_GetPsFile_Handler,
		},
		{
			MethodName: "GetPsFileByHash",
			Handler:    _PsFileService_GetPsFileByHash_Handler,
		},
		{
			MethodName: "CheckPsFileExists",
			Handler:    _PsFileService_CheckPsFileExists_Handler,
		},
		{
			MethodName: "ListPsFiles",
			Handler:    _PsFileService_ListPsFiles_Handler,
		},
		{
			MethodName: "UpdatePsFileStatus",
			Handler:    _PsFileService_UpdatePsFileStatus_Handler,
		},
		{
			MethodName: "IncrementReferenceCount",
			Handler:    _PsFileService_IncrementReferenceCount_Handler,
		},
		{
			MethodName: "DecrementReferenceCount",
			Handler:    _PsFileService_DecrementReferenceCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/v1/ps_file.proto",
}
