// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: storage/v1/subscription.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	v1 "storage/api/common/v1"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscription struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId    string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExpiredAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expired_at,json=expiredAt,proto3,oneof" json:"expired_at,omitempty"`
	Status    string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // active | expired | canceled
	CreatedBy *string                `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Embedded plan info (optional, for convenience)
	Plan          *Plan `protobuf:"bytes,10,opt,name=plan,proto3,oneof" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_storage_v1_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Subscription) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Subscription) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Subscription) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Subscription) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

// CreateSubscription
type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"` // Default: now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_storage_v1_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type CreateSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_storage_v1_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// GetSubscription
type GetSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_storage_v1_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubscriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_storage_v1_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// GetUserActiveSubscription
type GetUserActiveSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActiveSubscriptionRequest) Reset() {
	*x = GetUserActiveSubscriptionRequest{}
	mi := &file_storage_v1_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActiveSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActiveSubscriptionRequest) ProtoMessage() {}

func (x *GetUserActiveSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActiveSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetUserActiveSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserActiveSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserActiveSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3,oneof" json:"subscription,omitempty"` // null if no active subscription
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActiveSubscriptionResponse) Reset() {
	*x = GetUserActiveSubscriptionResponse{}
	mi := &file_storage_v1_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActiveSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActiveSubscriptionResponse) ProtoMessage() {}

func (x *GetUserActiveSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActiveSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetUserActiveSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserActiveSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// ListSubscriptions
type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Pagination    *v1.CursorPaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        *string                     `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"` // Filter by status: active, expired, canceled
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_storage_v1_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *ListSubscriptionsRequest) GetPagination() *v1.CursorPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListSubscriptionsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Subscriptions []*Subscription              `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Pagination    *v1.CursorPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_storage_v1_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *ListSubscriptionsResponse) GetPagination() *v1.CursorPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListUserSubscriptions
type ListUserSubscriptionsRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	UserId        string                      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *v1.CursorPaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSubscriptionsRequest) Reset() {
	*x = ListUserSubscriptionsRequest{}
	mi := &file_storage_v1_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSubscriptionsRequest) ProtoMessage() {}

func (x *ListUserSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListUserSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserSubscriptionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserSubscriptionsRequest) GetPagination() *v1.CursorPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListUserSubscriptionsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Subscriptions []*Subscription              `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Pagination    *v1.CursorPaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSubscriptionsResponse) Reset() {
	*x = ListUserSubscriptionsResponse{}
	mi := &file_storage_v1_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSubscriptionsResponse) ProtoMessage() {}

func (x *ListUserSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListUserSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *ListUserSubscriptionsResponse) GetPagination() *v1.CursorPaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// CancelSubscription
type CancelSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_storage_v1_subscription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{11}
}

func (x *CancelSubscriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionResponse) Reset() {
	*x = CancelSubscriptionResponse{}
	mi := &file_storage_v1_subscription_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionResponse) ProtoMessage() {}

func (x *CancelSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{12}
}

func (x *CancelSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// ExpireSubscription
type ExpireSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireSubscriptionRequest) Reset() {
	*x = ExpireSubscriptionRequest{}
	mi := &file_storage_v1_subscription_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireSubscriptionRequest) ProtoMessage() {}

func (x *ExpireSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ExpireSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{13}
}

func (x *ExpireSubscriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ExpireSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireSubscriptionResponse) Reset() {
	*x = ExpireSubscriptionResponse{}
	mi := &file_storage_v1_subscription_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireSubscriptionResponse) ProtoMessage() {}

func (x *ExpireSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*ExpireSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{14}
}

func (x *ExpireSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// ExpireAllDueSubscriptions
type ExpireAllDueSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireAllDueSubscriptionsRequest) Reset() {
	*x = ExpireAllDueSubscriptionsRequest{}
	mi := &file_storage_v1_subscription_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireAllDueSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireAllDueSubscriptionsRequest) ProtoMessage() {}

func (x *ExpireAllDueSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireAllDueSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ExpireAllDueSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{15}
}

type ExpireAllDueSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiredCount  int32                  `protobuf:"varint,1,opt,name=expired_count,json=expiredCount,proto3" json:"expired_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireAllDueSubscriptionsResponse) Reset() {
	*x = ExpireAllDueSubscriptionsResponse{}
	mi := &file_storage_v1_subscription_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireAllDueSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireAllDueSubscriptionsResponse) ProtoMessage() {}

func (x *ExpireAllDueSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireAllDueSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ExpireAllDueSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{16}
}

func (x *ExpireAllDueSubscriptionsResponse) GetExpiredCount() int32 {
	if x != nil {
		return x.ExpiredCount
	}
	return 0
}

// ResetExpiredQuotas
type ResetExpiredQuotasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetExpiredQuotasRequest) Reset() {
	*x = ResetExpiredQuotasRequest{}
	mi := &file_storage_v1_subscription_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetExpiredQuotasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetExpiredQuotasRequest) ProtoMessage() {}

func (x *ResetExpiredQuotasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetExpiredQuotasRequest.ProtoReflect.Descriptor instead.
func (*ResetExpiredQuotasRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{17}
}

type ResetExpiredQuotasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResetCount    int32                  `protobuf:"varint,1,opt,name=reset_count,json=resetCount,proto3" json:"reset_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetExpiredQuotasResponse) Reset() {
	*x = ResetExpiredQuotasResponse{}
	mi := &file_storage_v1_subscription_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetExpiredQuotasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetExpiredQuotasResponse) ProtoMessage() {}

func (x *ResetExpiredQuotasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_subscription_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetExpiredQuotasResponse.ProtoReflect.Descriptor instead.
func (*ResetExpiredQuotasResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_subscription_proto_rawDescGZIP(), []int{18}
}

func (x *ResetExpiredQuotasResponse) GetResetCount() int32 {
	if x != nil {
		return x.ResetCount
	}
	return 0
}

var File_storage_v1_subscription_proto protoreflect.FileDescriptor

const file_storage_v1_subscription_proto_rawDesc = "" +
	"\n" +
	"\x1dstorage/v1/subscription.proto\x12\n" +
	"storage.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1acommon/v1/pagination.proto\x1a\x15storage/v1/plan.proto\"\xcf\x03\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12>\n" +
	"\n" +
	"expired_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiredAt\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\"\n" +
	"\n" +
	"created_by\x18\a \x01(\tH\x01R\tcreatedBy\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12)\n" +
	"\x04plan\x18\n" +
	" \x01(\v2\x10.storage.v1.PlanH\x02R\x04plan\x88\x01\x01B\r\n" +
	"\v_expired_atB\r\n" +
	"\v_created_byB\a\n" +
	"\x05_plan\"\x9c\x01\n" +
	"\x19CreateSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12>\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartedAt\x88\x01\x01B\r\n" +
	"\v_started_at\"Z\n" +
	"\x1aCreateSubscriptionResponse\x12<\n" +
	"\fsubscription\x18\x01 \x01(\v2\x18.storage.v1.SubscriptionR\fsubscription\"(\n" +
	"\x16GetSubscriptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x17GetSubscriptionResponse\x12<\n" +
	"\fsubscription\x18\x01 \x01(\v2\x18.storage.v1.SubscriptionR\fsubscription\";\n" +
	" GetUserActiveSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"w\n" +
	"!GetUserActiveSubscriptionResponse\x12A\n" +
	"\fsubscription\x18\x01 \x01(\v2\x18.storage.v1.SubscriptionH\x00R\fsubscription\x88\x01\x01B\x0f\n" +
	"\r_subscription\"\x86\x01\n" +
	"\x18ListSubscriptionsRequest\x12B\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\".common.v1.CursorPaginationRequestR\n" +
	"pagination\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\xa0\x01\n" +
	"\x19ListSubscriptionsResponse\x12>\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x18.storage.v1.SubscriptionR\rsubscriptions\x12C\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2#.common.v1.CursorPaginationResponseR\n" +
	"pagination\"{\n" +
	"\x1cListUserSubscriptionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12B\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\".common.v1.CursorPaginationRequestR\n" +
	"pagination\"\xa4\x01\n" +
	"\x1dListUserSubscriptionsResponse\x12>\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x18.storage.v1.SubscriptionR\rsubscriptions\x12C\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2#.common.v1.CursorPaginationResponseR\n" +
	"pagination\"+\n" +
	"\x19CancelSubscriptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x1aCancelSubscriptionResponse\x12<\n" +
	"\fsubscription\x18\x01 \x01(\v2\x18.storage.v1.SubscriptionR\fsubscription\"+\n" +
	"\x19ExpireSubscriptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x1aExpireSubscriptionResponse\x12<\n" +
	"\fsubscription\x18\x01 \x01(\v2\x18.storage.v1.SubscriptionR\fsubscription\"\"\n" +
	" ExpireAllDueSubscriptionsRequest\"H\n" +
	"!ExpireAllDueSubscriptionsResponse\x12#\n" +
	"\rexpired_count\x18\x01 \x01(\x05R\fexpiredCount\"\x1b\n" +
	"\x19ResetExpiredQuotasRequest\"=\n" +
	"\x1aResetExpiredQuotasResponse\x12\x1f\n" +
	"\vreset_count\x18\x01 \x01(\x05R\n" +
	"resetCount2\xa6\n" +
	"\n" +
	"\x13SubscriptionService\x12\x81\x01\n" +
	"\x12CreateSubscription\x12%.storage.v1.CreateSubscriptionRequest\x1a&.storage.v1.CreateSubscriptionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/subscriptions\x12z\n" +
	"\x0fGetSubscription\x12\".storage.v1.GetSubscriptionRequest\x1a#.storage.v1.GetSubscriptionResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/subscriptions/{id}\x12\xa2\x01\n" +
	"\x19GetUserActiveSubscription\x12,.storage.v1.GetUserActiveSubscriptionRequest\x1a-.storage.v1.GetUserActiveSubscriptionResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/users/{user_id}/subscription\x12{\n" +
	"\x11ListSubscriptions\x12$.storage.v1.ListSubscriptionsRequest\x1a%.storage.v1.ListSubscriptionsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/subscriptions\x12\x97\x01\n" +
	"\x15ListUserSubscriptions\x12(.storage.v1.ListUserSubscriptionsRequest\x1a).storage.v1.ListUserSubscriptionsResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/users/{user_id}/subscriptions\x12\x8d\x01\n" +
	"\x12CancelSubscription\x12%.storage.v1.CancelSubscriptionRequest\x1a&.storage.v1.CancelSubscriptionResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/subscriptions/{id}/cancel\x12\x8d\x01\n" +
	"\x12ExpireSubscription\x12%.storage.v1.ExpireSubscriptionRequest\x1a&.storage.v1.ExpireSubscriptionResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/subscriptions/{id}/expire\x12\xa1\x01\n" +
	"\x19ExpireAllDueSubscriptions\x12,.storage.v1.ExpireAllDueSubscriptionsRequest\x1a-.storage.v1.ExpireAllDueSubscriptionsResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/subscriptions/expire-due\x12\x8e\x01\n" +
	"\x12ResetExpiredQuotas\x12%.storage.v1.ResetExpiredQuotasRequest\x1a&.storage.v1.ResetExpiredQuotasResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/subscriptions/reset-quotasB\x1bZ\x19storage/api/storage/v1;v1b\x06proto3"

var (
	file_storage_v1_subscription_proto_rawDescOnce sync.Once
	file_storage_v1_subscription_proto_rawDescData []byte
)

func file_storage_v1_subscription_proto_rawDescGZIP() []byte {
	file_storage_v1_subscription_proto_rawDescOnce.Do(func() {
		file_storage_v1_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v1_subscription_proto_rawDesc), len(file_storage_v1_subscription_proto_rawDesc)))
	})
	return file_storage_v1_subscription_proto_rawDescData
}

var file_storage_v1_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_storage_v1_subscription_proto_goTypes = []any{
	(*Subscription)(nil),                      // 0: storage.v1.Subscription
	(*CreateSubscriptionRequest)(nil),         // 1: storage.v1.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil),        // 2: storage.v1.CreateSubscriptionResponse
	(*GetSubscriptionRequest)(nil),            // 3: storage.v1.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),           // 4: storage.v1.GetSubscriptionResponse
	(*GetUserActiveSubscriptionRequest)(nil),  // 5: storage.v1.GetUserActiveSubscriptionRequest
	(*GetUserActiveSubscriptionResponse)(nil), // 6: storage.v1.GetUserActiveSubscriptionResponse
	(*ListSubscriptionsRequest)(nil),          // 7: storage.v1.ListSubscriptionsRequest
	(*ListSubscriptionsResponse)(nil),         // 8: storage.v1.ListSubscriptionsResponse
	(*ListUserSubscriptionsRequest)(nil),      // 9: storage.v1.ListUserSubscriptionsRequest
	(*ListUserSubscriptionsResponse)(nil),     // 10: storage.v1.ListUserSubscriptionsResponse
	(*CancelSubscriptionRequest)(nil),         // 11: storage.v1.CancelSubscriptionRequest
	(*CancelSubscriptionResponse)(nil),        // 12: storage.v1.CancelSubscriptionResponse
	(*ExpireSubscriptionRequest)(nil),         // 13: storage.v1.ExpireSubscriptionRequest
	(*ExpireSubscriptionResponse)(nil),        // 14: storage.v1.ExpireSubscriptionResponse
	(*ExpireAllDueSubscriptionsRequest)(nil),  // 15: storage.v1.ExpireAllDueSubscriptionsRequest
	(*ExpireAllDueSubscriptionsResponse)(nil), // 16: storage.v1.ExpireAllDueSubscriptionsResponse
	(*ResetExpiredQuotasRequest)(nil),         // 17: storage.v1.ResetExpiredQuotasRequest
	(*ResetExpiredQuotasResponse)(nil),        // 18: storage.v1.ResetExpiredQuotasResponse
	(*timestamppb.Timestamp)(nil),             // 19: google.protobuf.Timestamp
	(*Plan)(nil),                              // 20: storage.v1.Plan
	(*v1.CursorPaginationRequest)(nil),        // 21: common.v1.CursorPaginationRequest
	(*v1.CursorPaginationResponse)(nil),       // 22: common.v1.CursorPaginationResponse
}
var file_storage_v1_subscription_proto_depIdxs = []int32{
	19, // 0: storage.v1.Subscription.started_at:type_name -> google.protobuf.Timestamp
	19, // 1: storage.v1.Subscription.expired_at:type_name -> google.protobuf.Timestamp
	19, // 2: storage.v1.Subscription.created_at:type_name -> google.protobuf.Timestamp
	19, // 3: storage.v1.Subscription.updated_at:type_name -> google.protobuf.Timestamp
	20, // 4: storage.v1.Subscription.plan:type_name -> storage.v1.Plan
	19, // 5: storage.v1.CreateSubscriptionRequest.started_at:type_name -> google.protobuf.Timestamp
	0,  // 6: storage.v1.CreateSubscriptionResponse.subscription:type_name -> storage.v1.Subscription
	0,  // 7: storage.v1.GetSubscriptionResponse.subscription:type_name -> storage.v1.Subscription
	0,  // 8: storage.v1.GetUserActiveSubscriptionResponse.subscription:type_name -> storage.v1.Subscription
	21, // 9: storage.v1.ListSubscriptionsRequest.pagination:type_name -> common.v1.CursorPaginationRequest
	0,  // 10: storage.v1.ListSubscriptionsResponse.subscriptions:type_name -> storage.v1.Subscription
	22, // 11: storage.v1.ListSubscriptionsResponse.pagination:type_name -> common.v1.CursorPaginationResponse
	21, // 12: storage.v1.ListUserSubscriptionsRequest.pagination:type_name -> common.v1.CursorPaginationRequest
	0,  // 13: storage.v1.ListUserSubscriptionsResponse.subscriptions:type_name -> storage.v1.Subscription
	22, // 14: storage.v1.ListUserSubscriptionsResponse.pagination:type_name -> common.v1.CursorPaginationResponse
	0,  // 15: storage.v1.CancelSubscriptionResponse.subscription:type_name -> storage.v1.Subscription
	0,  // 16: storage.v1.ExpireSubscriptionResponse.subscription:type_name -> storage.v1.Subscription
	1,  // 17: storage.v1.SubscriptionService.CreateSubscription:input_type -> storage.v1.CreateSubscriptionRequest
	3,  // 18: storage.v1.SubscriptionService.GetSubscription:input_type -> storage.v1.GetSubscriptionRequest
	5,  // 19: storage.v1.SubscriptionService.GetUserActiveSubscription:input_type -> storage.v1.GetUserActiveSubscriptionRequest
	7,  // 20: storage.v1.SubscriptionService.ListSubscriptions:input_type -> storage.v1.ListSubscriptionsRequest
	9,  // 21: storage.v1.SubscriptionService.ListUserSubscriptions:input_type -> storage.v1.ListUserSubscriptionsRequest
	11, // 22: storage.v1.SubscriptionService.CancelSubscription:input_type -> storage.v1.CancelSubscriptionRequest
	13, // 23: storage.v1.SubscriptionService.ExpireSubscription:input_type -> storage.v1.ExpireSubscriptionRequest
	15, // 24: storage.v1.SubscriptionService.ExpireAllDueSubscriptions:input_type -> storage.v1.ExpireAllDueSubscriptionsRequest
	17, // 25: storage.v1.SubscriptionService.ResetExpiredQuotas:input_type -> storage.v1.ResetExpiredQuotasRequest
	2,  // 26: storage.v1.SubscriptionService.CreateSubscription:output_type -> storage.v1.CreateSubscriptionResponse
	4,  // 27: storage.v1.SubscriptionService.GetSubscription:output_type -> storage.v1.GetSubscriptionResponse
	6,  // 28: storage.v1.SubscriptionService.GetUserActiveSubscription:output_type -> storage.v1.GetUserActiveSubscriptionResponse
	8,  // 29: storage.v1.SubscriptionService.ListSubscriptions:output_type -> storage.v1.ListSubscriptionsResponse
	10, // 30: storage.v1.SubscriptionService.ListUserSubscriptions:output_type -> storage.v1.ListUserSubscriptionsResponse
	12, // 31: storage.v1.SubscriptionService.CancelSubscription:output_type -> storage.v1.CancelSubscriptionResponse
	14, // 32: storage.v1.SubscriptionService.ExpireSubscription:output_type -> storage.v1.ExpireSubscriptionResponse
	16, // 33: storage.v1.SubscriptionService.ExpireAllDueSubscriptions:output_type -> storage.v1.ExpireAllDueSubscriptionsResponse
	18, // 34: storage.v1.SubscriptionService.ResetExpiredQuotas:output_type -> storage.v1.ResetExpiredQuotasResponse
	26, // [26:35] is the sub-list for method output_type
	17, // [17:26] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_storage_v1_subscription_proto_init() }
func file_storage_v1_subscription_proto_init() {
	if File_storage_v1_subscription_proto != nil {
		return
	}
	file_storage_v1_plan_proto_init()
	file_storage_v1_subscription_proto_msgTypes[0].OneofWrappers = []any{}
	file_storage_v1_subscription_proto_msgTypes[1].OneofWrappers = []any{}
	file_storage_v1_subscription_proto_msgTypes[6].OneofWrappers = []any{}
	file_storage_v1_subscription_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v1_subscription_proto_rawDesc), len(file_storage_v1_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_v1_subscription_proto_goTypes,
		DependencyIndexes: file_storage_v1_subscription_proto_depIdxs,
		MessageInfos:      file_storage_v1_subscription_proto_msgTypes,
	}.Build()
	File_storage_v1_subscription_proto = out.File
	file_storage_v1_subscription_proto_goTypes = nil
	file_storage_v1_subscription_proto_depIdxs = nil
}
