// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"moderation/internal/biz"
	"moderation/internal/conf"
	"moderation/internal/data"
	"moderation/internal/server"
	"moderation/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, moderation *conf.Moderation, logger log.Logger) (*kratos.App, func(), error) {
	cache, cleanup, err := data.NewRedisCache(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	textModerator := data.NewTextModerator(cache, moderation, logger)
	grpcClient, cleanup2, err := data.NewNSFWClient(moderation, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup3, err := data.NewData(confData, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	badImageRepo := data.NewBadImageRepo(dataData, logger)
	localImageModerator := data.NewImageModerator(textModerator, cache, grpcClient, badImageRepo, logger)
	localVideoModerator := data.NewVideoModerator(localImageModerator, textModerator, logger)
	badwordRepo := data.NewBadwordRepo(dataData, logger)
	moderationUsecase := biz.NewModerationUsecase(textModerator, localImageModerator, localVideoModerator, badwordRepo, logger)
	moderationService := service.NewModerationService(moderationUsecase)
	badwordUsecase := biz.NewBadwordUsecase(badwordRepo, logger)
	adminService := service.NewAdminService(badwordUsecase, moderationUsecase)
	grpcServer := server.NewGRPCServer(confServer, moderationService, adminService, logger)
	httpServer := server.NewHTTPServer(confServer, moderationService, adminService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
