// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"moderation/internal/biz"
	"moderation/internal/conf"
	"moderation/internal/data"
	"moderation/internal/server"
	"moderation/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, moderation *conf.Moderation, logger log.Logger) (*kratos.App, func(), error) {
	cache, cleanup, err := data.NewRedisCache(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	textClient, cleanup2, err := data.NewNSFWTextClient(moderation, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup3, err := data.NewData(confData, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	textCacheRepo := data.NewTextCacheRepo(dataData, logger)
	textModerator := data.NewTextModerator(cache, textClient, textCacheRepo, moderation, logger)
	imageClient, cleanup4, err := data.NewNSFWImageClient(moderation, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	imageCacheRepo := data.NewImageCacheRepo(dataData, logger)
	localImageModerator := data.NewImageModerator(textModerator, cache, imageClient, imageCacheRepo, logger)
	localVideoModerator := data.NewVideoModerator(localImageModerator, textModerator, logger)
	moderationUsecase := biz.NewModerationUsecase(textModerator, localImageModerator, localVideoModerator, textCacheRepo, imageCacheRepo, logger)
	moderationService := service.NewModerationService(moderationUsecase)
	adminService := service.NewAdminService(moderationUsecase)
	grpcServer := server.NewGRPCServer(confServer, moderationService, adminService, logger)
	httpServer := server.NewHTTPServer(confServer, moderationService, adminService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
