// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: nsfw_text.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NSFWTextDetector_Predict_FullMethodName      = "/nsfw_text.v1.NSFWTextDetector/Predict"
	NSFWTextDetector_PredictBatch_FullMethodName = "/nsfw_text.v1.NSFWTextDetector/PredictBatch"
	NSFWTextDetector_HealthCheck_FullMethodName  = "/nsfw_text.v1.NSFWTextDetector/HealthCheck"
)

// NSFWTextDetectorClient is the client API for NSFWTextDetector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NSFWTextDetector service for detecting NSFW/unsafe content in text
// using Qwen3Guard-Gen-0.6B.
type NSFWTextDetectorClient interface {
	// Predict safety of a single text.
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	// Predict safety for a batch of texts.
	PredictBatch(ctx context.Context, in *PredictBatchRequest, opts ...grpc.CallOption) (*PredictBatchResponse, error)
	// Health check.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type nSFWTextDetectorClient struct {
	cc grpc.ClientConnInterface
}

func NewNSFWTextDetectorClient(cc grpc.ClientConnInterface) NSFWTextDetectorClient {
	return &nSFWTextDetectorClient{cc}
}

func (c *nSFWTextDetectorClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, NSFWTextDetector_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSFWTextDetectorClient) PredictBatch(ctx context.Context, in *PredictBatchRequest, opts ...grpc.CallOption) (*PredictBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictBatchResponse)
	err := c.cc.Invoke(ctx, NSFWTextDetector_PredictBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSFWTextDetectorClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NSFWTextDetector_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NSFWTextDetectorServer is the server API for NSFWTextDetector service.
// All implementations must embed UnimplementedNSFWTextDetectorServer
// for forward compatibility.
//
// NSFWTextDetector service for detecting NSFW/unsafe content in text
// using Qwen3Guard-Gen-0.6B.
type NSFWTextDetectorServer interface {
	// Predict safety of a single text.
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	// Predict safety for a batch of texts.
	PredictBatch(context.Context, *PredictBatchRequest) (*PredictBatchResponse, error)
	// Health check.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedNSFWTextDetectorServer()
}

// UnimplementedNSFWTextDetectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNSFWTextDetectorServer struct{}

func (UnimplementedNSFWTextDetectorServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedNSFWTextDetectorServer) PredictBatch(context.Context, *PredictBatchRequest) (*PredictBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PredictBatch not implemented")
}
func (UnimplementedNSFWTextDetectorServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNSFWTextDetectorServer) mustEmbedUnimplementedNSFWTextDetectorServer() {}
func (UnimplementedNSFWTextDetectorServer) testEmbeddedByValue()                          {}

// UnsafeNSFWTextDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NSFWTextDetectorServer will
// result in compilation errors.
type UnsafeNSFWTextDetectorServer interface {
	mustEmbedUnimplementedNSFWTextDetectorServer()
}

func RegisterNSFWTextDetectorServer(s grpc.ServiceRegistrar, srv NSFWTextDetectorServer) {
	// If the following call panics, it indicates UnimplementedNSFWTextDetectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NSFWTextDetector_ServiceDesc, srv)
}

func _NSFWTextDetector_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWTextDetectorServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFWTextDetector_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWTextDetectorServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSFWTextDetector_PredictBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWTextDetectorServer).PredictBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFWTextDetector_PredictBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWTextDetectorServer).PredictBatch(ctx, req.(*PredictBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSFWTextDetector_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWTextDetectorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFWTextDetector_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWTextDetectorServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NSFWTextDetector_ServiceDesc is the grpc.ServiceDesc for NSFWTextDetector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NSFWTextDetector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nsfw_text.v1.NSFWTextDetector",
	HandlerType: (*NSFWTextDetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _NSFWTextDetector_Predict_Handler,
		},
		{
			MethodName: "PredictBatch",
			Handler:    _NSFWTextDetector_PredictBatch_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NSFWTextDetector_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nsfw_text.proto",
}
