// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: nsfw_image.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NSFWImageDetector_Predict_FullMethodName              = "/nsfw.v1.NSFWImageDetector/Predict"
	NSFWImageDetector_PredictFromURL_FullMethodName       = "/nsfw.v1.NSFWImageDetector/PredictFromURL"
	NSFWImageDetector_PredictBatchFromURLs_FullMethodName = "/nsfw.v1.NSFWImageDetector/PredictBatchFromURLs"
	NSFWImageDetector_HealthCheck_FullMethodName          = "/nsfw.v1.NSFWImageDetector/HealthCheck"
)

// NSFWImageDetectorClient is the client API for NSFWImageDetector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NSFWImageDetector service for detecting NSFW content in images.
type NSFWImageDetectorClient interface {
	// Predict NSFW content from raw image bytes.
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	// Predict NSFW content from a public image URL.
	PredictFromURL(ctx context.Context, in *PredictURLRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	// Predict NSFW content for a batch of images (by URL).
	PredictBatchFromURLs(ctx context.Context, in *PredictBatchURLRequest, opts ...grpc.CallOption) (*PredictBatchResponse, error)
	// Health check.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type nSFWImageDetectorClient struct {
	cc grpc.ClientConnInterface
}

func NewNSFWImageDetectorClient(cc grpc.ClientConnInterface) NSFWImageDetectorClient {
	return &nSFWImageDetectorClient{cc}
}

func (c *nSFWImageDetectorClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, NSFWImageDetector_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSFWImageDetectorClient) PredictFromURL(ctx context.Context, in *PredictURLRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, NSFWImageDetector_PredictFromURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSFWImageDetectorClient) PredictBatchFromURLs(ctx context.Context, in *PredictBatchURLRequest, opts ...grpc.CallOption) (*PredictBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictBatchResponse)
	err := c.cc.Invoke(ctx, NSFWImageDetector_PredictBatchFromURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSFWImageDetectorClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NSFWImageDetector_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NSFWImageDetectorServer is the server API for NSFWImageDetector service.
// All implementations must embed UnimplementedNSFWImageDetectorServer
// for forward compatibility.
//
// NSFWImageDetector service for detecting NSFW content in images.
type NSFWImageDetectorServer interface {
	// Predict NSFW content from raw image bytes.
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	// Predict NSFW content from a public image URL.
	PredictFromURL(context.Context, *PredictURLRequest) (*PredictResponse, error)
	// Predict NSFW content for a batch of images (by URL).
	PredictBatchFromURLs(context.Context, *PredictBatchURLRequest) (*PredictBatchResponse, error)
	// Health check.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedNSFWImageDetectorServer()
}

// UnimplementedNSFWImageDetectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNSFWImageDetectorServer struct{}

func (UnimplementedNSFWImageDetectorServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedNSFWImageDetectorServer) PredictFromURL(context.Context, *PredictURLRequest) (*PredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PredictFromURL not implemented")
}
func (UnimplementedNSFWImageDetectorServer) PredictBatchFromURLs(context.Context, *PredictBatchURLRequest) (*PredictBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PredictBatchFromURLs not implemented")
}
func (UnimplementedNSFWImageDetectorServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNSFWImageDetectorServer) mustEmbedUnimplementedNSFWImageDetectorServer() {}
func (UnimplementedNSFWImageDetectorServer) testEmbeddedByValue()                           {}

// UnsafeNSFWImageDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NSFWImageDetectorServer will
// result in compilation errors.
type UnsafeNSFWImageDetectorServer interface {
	mustEmbedUnimplementedNSFWImageDetectorServer()
}

func RegisterNSFWImageDetectorServer(s grpc.ServiceRegistrar, srv NSFWImageDetectorServer) {
	// If the following call panics, it indicates UnimplementedNSFWImageDetectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NSFWImageDetector_ServiceDesc, srv)
}

func _NSFWImageDetector_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWImageDetectorServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFWImageDetector_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWImageDetectorServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSFWImageDetector_PredictFromURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWImageDetectorServer).PredictFromURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFWImageDetector_PredictFromURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWImageDetectorServer).PredictFromURL(ctx, req.(*PredictURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSFWImageDetector_PredictBatchFromURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictBatchURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWImageDetectorServer).PredictBatchFromURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFWImageDetector_PredictBatchFromURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWImageDetectorServer).PredictBatchFromURLs(ctx, req.(*PredictBatchURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSFWImageDetector_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWImageDetectorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFWImageDetector_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWImageDetectorServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NSFWImageDetector_ServiceDesc is the grpc.ServiceDesc for NSFWImageDetector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NSFWImageDetector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nsfw.v1.NSFWImageDetector",
	HandlerType: (*NSFWImageDetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _NSFWImageDetector_Predict_Handler,
		},
		{
			MethodName: "PredictFromURL",
			Handler:    _NSFWImageDetector_PredictFromURL_Handler,
		},
		{
			MethodName: "PredictBatchFromURLs",
			Handler:    _NSFWImageDetector_PredictBatchFromURLs_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NSFWImageDetector_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nsfw_image.proto",
}
