// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server configuration
	Server *Server `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Data configuration
	Data *Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Moderation configuration
	Moderation    *Moderation `protobuf:"bytes,3,opt,name=moderation,proto3" json:"moderation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetModeration() *Moderation {
	if x != nil {
		return x.Moderation
	}
	return nil
}

type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP server
	Http *Server_HTTP `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	// gRPC server
	Grpc          *Server_GRPC `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Database connection
	Database *Data_Database `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Redis connection
	Redis         *Data_Redis `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Moderation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VLLM configuration
	Vllm *Moderation_VLLM `protobuf:"bytes,1,opt,name=vllm,proto3" json:"vllm,omitempty"`
	// PHash configuration
	Phash *Moderation_PHash `protobuf:"bytes,2,opt,name=phash,proto3" json:"phash,omitempty"`
	// Text moderation configuration
	Text *Moderation_TextModeration `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// NSFW detector configuration
	Nsfw *Moderation_NSFWDetector `protobuf:"bytes,4,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	// Moderator configuration
	Moderator     *Moderation_Moderator `protobuf:"bytes,5,opt,name=moderator,proto3" json:"moderator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moderation) Reset() {
	*x = Moderation{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moderation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moderation) ProtoMessage() {}

func (x *Moderation) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moderation.ProtoReflect.Descriptor instead.
func (*Moderation) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Moderation) GetVllm() *Moderation_VLLM {
	if x != nil {
		return x.Vllm
	}
	return nil
}

func (x *Moderation) GetPhash() *Moderation_PHash {
	if x != nil {
		return x.Phash
	}
	return nil
}

func (x *Moderation) GetText() *Moderation_TextModeration {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *Moderation) GetNsfw() *Moderation_NSFWDetector {
	if x != nil {
		return x.Nsfw
	}
	return nil
}

func (x *Moderation) GetModerator() *Moderation_Moderator {
	if x != nil {
		return x.Moderator
	}
	return nil
}

type Server_HTTP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP network
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// HTTP address
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// HTTP timeout
	Timeout       *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC network
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// gRPC address
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// gRPC timeout
	Timeout       *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Database driver
	Driver string `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	// Database source
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Database connection pool
	Pool          *Data_Database_Pool `protobuf:"bytes,3,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetPool() *Data_Database_Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

type Data_Redis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Redis network
	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// Redis address
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// Redis read timeout
	ReadTimeout *durationpb.Duration `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	// Redis write timeout
	WriteTimeout  *durationpb.Duration `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

type Data_Database_Pool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of open connections
	MaxOpenConns int32 `protobuf:"varint,1,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	// Minimum number of idle connections
	MinIdleConns int32 `protobuf:"varint,2,opt,name=min_idle_conns,json=minIdleConns,proto3" json:"min_idle_conns,omitempty"`
	// Maximum connection lifetime in minutes
	MaxConnLifetime int64 `protobuf:"varint,3,opt,name=max_conn_lifetime,json=maxConnLifetime,proto3" json:"max_conn_lifetime,omitempty"`
	// Maximum connection idle time in minutes
	MaxConnIdleTime int64 `protobuf:"varint,4,opt,name=max_conn_idle_time,json=maxConnIdleTime,proto3" json:"max_conn_idle_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_Database_Pool) Reset() {
	*x = Data_Database_Pool{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database_Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database_Pool) ProtoMessage() {}

func (x *Data_Database_Pool) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database_Pool.ProtoReflect.Descriptor instead.
func (*Data_Database_Pool) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Data_Database_Pool) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_Database_Pool) GetMinIdleConns() int32 {
	if x != nil {
		return x.MinIdleConns
	}
	return 0
}

func (x *Data_Database_Pool) GetMaxConnLifetime() int64 {
	if x != nil {
		return x.MaxConnLifetime
	}
	return 0
}

func (x *Data_Database_Pool) GetMaxConnIdleTime() int64 {
	if x != nil {
		return x.MaxConnIdleTime
	}
	return 0
}

type Moderation_VLLM struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enable VLLM
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// VLLM base URL
	BaseUrl string `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// VLLM model
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// VLLM timeout
	Timeout       *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moderation_VLLM) Reset() {
	*x = Moderation_VLLM{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moderation_VLLM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moderation_VLLM) ProtoMessage() {}

func (x *Moderation_VLLM) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moderation_VLLM.ProtoReflect.Descriptor instead.
func (*Moderation_VLLM) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Moderation_VLLM) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Moderation_VLLM) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Moderation_VLLM) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Moderation_VLLM) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Moderation_PHash struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enable PHash
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Hamming distance threshold (default 5)
	SimilarityThreshold int32 `protobuf:"varint,2,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Moderation_PHash) Reset() {
	*x = Moderation_PHash{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moderation_PHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moderation_PHash) ProtoMessage() {}

func (x *Moderation_PHash) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moderation_PHash.ProtoReflect.Descriptor instead.
func (*Moderation_PHash) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Moderation_PHash) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Moderation_PHash) GetSimilarityThreshold() int32 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

type Moderation_TextModeration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Severity threshold to auto-reject
	RejectThreshold int32 `protobuf:"varint,1,opt,name=reject_threshold,json=rejectThreshold,proto3" json:"reject_threshold,omitempty"`
	// Severity threshold for manual review
	ReviewThreshold int32 `protobuf:"varint,2,opt,name=review_threshold,json=reviewThreshold,proto3" json:"review_threshold,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Moderation_TextModeration) Reset() {
	*x = Moderation_TextModeration{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moderation_TextModeration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moderation_TextModeration) ProtoMessage() {}

func (x *Moderation_TextModeration) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moderation_TextModeration.ProtoReflect.Descriptor instead.
func (*Moderation_TextModeration) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Moderation_TextModeration) GetRejectThreshold() int32 {
	if x != nil {
		return x.RejectThreshold
	}
	return 0
}

func (x *Moderation_TextModeration) GetReviewThreshold() int32 {
	if x != nil {
		return x.ReviewThreshold
	}
	return 0
}

type Moderation_NSFWDetector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enable NSFW detector
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// gRPC address, e.g., "localhost:50051"
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// Request timeout
	Timeout *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Score threshold (default 0.5)
	Threshold     float32 `protobuf:"fixed32,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moderation_NSFWDetector) Reset() {
	*x = Moderation_NSFWDetector{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moderation_NSFWDetector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moderation_NSFWDetector) ProtoMessage() {}

func (x *Moderation_NSFWDetector) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moderation_NSFWDetector.ProtoReflect.Descriptor instead.
func (*Moderation_NSFWDetector) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 3}
}

func (x *Moderation_NSFWDetector) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Moderation_NSFWDetector) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Moderation_NSFWDetector) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Moderation_NSFWDetector) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type Moderation_Moderator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image moderation configuration
	ImageModerator *Moderation_Moderator_ImageModerator `protobuf:"bytes,1,opt,name=image_moderator,json=imageModerator,proto3" json:"image_moderator,omitempty"`
	// Text moderation configuration
	TextModerator *Moderation_Moderator_TextModerator `protobuf:"bytes,2,opt,name=text_moderator,json=textModerator,proto3" json:"text_moderator,omitempty"`
	// Video moderation configuration
	VideoModerator *Moderation_Moderator_VideoModerator `protobuf:"bytes,3,opt,name=video_moderator,json=videoModerator,proto3" json:"video_moderator,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Moderation_Moderator) Reset() {
	*x = Moderation_Moderator{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moderation_Moderator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moderation_Moderator) ProtoMessage() {}

func (x *Moderation_Moderator) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moderation_Moderator.ProtoReflect.Descriptor instead.
func (*Moderation_Moderator) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 4}
}

func (x *Moderation_Moderator) GetImageModerator() *Moderation_Moderator_ImageModerator {
	if x != nil {
		return x.ImageModerator
	}
	return nil
}

func (x *Moderation_Moderator) GetTextModerator() *Moderation_Moderator_TextModerator {
	if x != nil {
		return x.TextModerator
	}
	return nil
}

func (x *Moderation_Moderator) GetVideoModerator() *Moderation_Moderator_VideoModerator {
	if x != nil {
		return x.VideoModerator
	}
	return nil
}

type Moderation_Moderator_ImageModerator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of workers
	Workers int32 `protobuf:"varint,1,opt,name=workers,proto3" json:"workers,omitempty"`
	// NSFW threshold
	NsfwThreshold float32 `protobuf:"fixed32,2,opt,name=nsfw_threshold,json=nsfwThreshold,proto3" json:"nsfw_threshold,omitempty"`
	// Violence threshold
	ViolenceThreshold float32 `protobuf:"fixed32,3,opt,name=violence_threshold,json=violenceThreshold,proto3" json:"violence_threshold,omitempty"`
	// Enable OCR
	EnableOcr bool `protobuf:"varint,4,opt,name=enable_ocr,json=enableOcr,proto3" json:"enable_ocr,omitempty"`
	// Request timeout
	Timeout *durationpb.Duration `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Bloom filter size in bits
	BloomBits uint32 `protobuf:"varint,6,opt,name=bloom_bits,json=bloomBits,proto3" json:"bloom_bits,omitempty"`
	// Number of hash functions for Bloom filter
	BloomHashFuncs uint32 `protobuf:"varint,7,opt,name=bloom_hash_funcs,json=bloomHashFuncs,proto3" json:"bloom_hash_funcs,omitempty"`
	// Bloom filter key
	BloomKey      string `protobuf:"bytes,8,opt,name=bloom_key,json=bloomKey,proto3" json:"bloom_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moderation_Moderator_ImageModerator) Reset() {
	*x = Moderation_Moderator_ImageModerator{}
	mi := &file_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moderation_Moderator_ImageModerator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moderation_Moderator_ImageModerator) ProtoMessage() {}

func (x *Moderation_Moderator_ImageModerator) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moderation_Moderator_ImageModerator.ProtoReflect.Descriptor instead.
func (*Moderation_Moderator_ImageModerator) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 4, 0}
}

func (x *Moderation_Moderator_ImageModerator) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *Moderation_Moderator_ImageModerator) GetNsfwThreshold() float32 {
	if x != nil {
		return x.NsfwThreshold
	}
	return 0
}

func (x *Moderation_Moderator_ImageModerator) GetViolenceThreshold() float32 {
	if x != nil {
		return x.ViolenceThreshold
	}
	return 0
}

func (x *Moderation_Moderator_ImageModerator) GetEnableOcr() bool {
	if x != nil {
		return x.EnableOcr
	}
	return false
}

func (x *Moderation_Moderator_ImageModerator) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Moderation_Moderator_ImageModerator) GetBloomBits() uint32 {
	if x != nil {
		return x.BloomBits
	}
	return 0
}

func (x *Moderation_Moderator_ImageModerator) GetBloomHashFuncs() uint32 {
	if x != nil {
		return x.BloomHashFuncs
	}
	return 0
}

func (x *Moderation_Moderator_ImageModerator) GetBloomKey() string {
	if x != nil {
		return x.BloomKey
	}
	return ""
}

type Moderation_Moderator_TextModerator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bloom filter size in bits
	BloomBits uint32 `protobuf:"varint,1,opt,name=bloom_bits,json=bloomBits,proto3" json:"bloom_bits,omitempty"`
	// Number of hash functions for Bloom filter
	BloomHashFuncs uint32 `protobuf:"varint,2,opt,name=bloom_hash_funcs,json=bloomHashFuncs,proto3" json:"bloom_hash_funcs,omitempty"`
	// Bloom filter key
	BloomKey string `protobuf:"bytes,3,opt,name=bloom_key,json=bloomKey,proto3" json:"bloom_key,omitempty"`
	// Severity threshold to auto-reject
	RejectThreshold int32 `protobuf:"varint,4,opt,name=reject_threshold,json=rejectThreshold,proto3" json:"reject_threshold,omitempty"`
	// Severity threshold for manual review
	ReviewThreshold int32 `protobuf:"varint,5,opt,name=review_threshold,json=reviewThreshold,proto3" json:"review_threshold,omitempty"`
	// Enable LLM
	EnableLlm bool `protobuf:"varint,6,opt,name=enable_llm,json=enableLlm,proto3" json:"enable_llm,omitempty"`
	// LLM base URL
	VllmBaseUrl string `protobuf:"bytes,7,opt,name=vllm_base_url,json=vllmBaseUrl,proto3" json:"vllm_base_url,omitempty"`
	// LLM model
	VllmModel string `protobuf:"bytes,8,opt,name=vllm_model,json=vllmModel,proto3" json:"vllm_model,omitempty"`
	// LLM timeout
	VllmTimeout   *durationpb.Duration `protobuf:"bytes,9,opt,name=vllm_timeout,json=vllmTimeout,proto3" json:"vllm_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moderation_Moderator_TextModerator) Reset() {
	*x = Moderation_Moderator_TextModerator{}
	mi := &file_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moderation_Moderator_TextModerator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moderation_Moderator_TextModerator) ProtoMessage() {}

func (x *Moderation_Moderator_TextModerator) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moderation_Moderator_TextModerator.ProtoReflect.Descriptor instead.
func (*Moderation_Moderator_TextModerator) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 4, 1}
}

func (x *Moderation_Moderator_TextModerator) GetBloomBits() uint32 {
	if x != nil {
		return x.BloomBits
	}
	return 0
}

func (x *Moderation_Moderator_TextModerator) GetBloomHashFuncs() uint32 {
	if x != nil {
		return x.BloomHashFuncs
	}
	return 0
}

func (x *Moderation_Moderator_TextModerator) GetBloomKey() string {
	if x != nil {
		return x.BloomKey
	}
	return ""
}

func (x *Moderation_Moderator_TextModerator) GetRejectThreshold() int32 {
	if x != nil {
		return x.RejectThreshold
	}
	return 0
}

func (x *Moderation_Moderator_TextModerator) GetReviewThreshold() int32 {
	if x != nil {
		return x.ReviewThreshold
	}
	return 0
}

func (x *Moderation_Moderator_TextModerator) GetEnableLlm() bool {
	if x != nil {
		return x.EnableLlm
	}
	return false
}

func (x *Moderation_Moderator_TextModerator) GetVllmBaseUrl() string {
	if x != nil {
		return x.VllmBaseUrl
	}
	return ""
}

func (x *Moderation_Moderator_TextModerator) GetVllmModel() string {
	if x != nil {
		return x.VllmModel
	}
	return ""
}

func (x *Moderation_Moderator_TextModerator) GetVllmTimeout() *durationpb.Duration {
	if x != nil {
		return x.VllmTimeout
	}
	return nil
}

type Moderation_Moderator_VideoModerator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sample 1 frame per N seconds
	FrameSampleRate int32 `protobuf:"varint,1,opt,name=frame_sample_rate,json=frameSampleRate,proto3" json:"frame_sample_rate,omitempty"`
	// Maximum number of frames to check
	MaxFramesToCheck int32 `protobuf:"varint,2,opt,name=max_frames_to_check,json=maxFramesToCheck,proto3" json:"max_frames_to_check,omitempty"`
	// Enable audio transcription and moderation
	EnableAudioCheck bool `protobuf:"varint,3,opt,name=enable_audio_check,json=enableAudioCheck,proto3" json:"enable_audio_check,omitempty"`
	// Request timeout
	Timeout       *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moderation_Moderator_VideoModerator) Reset() {
	*x = Moderation_Moderator_VideoModerator{}
	mi := &file_conf_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moderation_Moderator_VideoModerator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moderation_Moderator_VideoModerator) ProtoMessage() {}

func (x *Moderation_Moderator_VideoModerator) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moderation_Moderator_VideoModerator.ProtoReflect.Descriptor instead.
func (*Moderation_Moderator_VideoModerator) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 4, 2}
}

func (x *Moderation_Moderator_VideoModerator) GetFrameSampleRate() int32 {
	if x != nil {
		return x.FrameSampleRate
	}
	return 0
}

func (x *Moderation_Moderator_VideoModerator) GetMaxFramesToCheck() int32 {
	if x != nil {
		return x.MaxFramesToCheck
	}
	return 0
}

func (x *Moderation_Moderator_VideoModerator) GetEnableAudioCheck() bool {
	if x != nil {
		return x.EnableAudioCheck
	}
	return false
}

func (x *Moderation_Moderator_VideoModerator) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\x95\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x126\n" +
	"\n" +
	"moderation\x18\x03 \x01(\v2\x16.kratos.api.ModerationR\n" +
	"moderation\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xc0\x04\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x1a\x9c\x02\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x122\n" +
	"\x04pool\x18\x03 \x01(\v2\x1e.kratos.api.Data.Database.PoolR\x04pool\x1a\xab\x01\n" +
	"\x04Pool\x12$\n" +
	"\x0emax_open_conns\x18\x01 \x01(\x05R\fmaxOpenConns\x12$\n" +
	"\x0emin_idle_conns\x18\x02 \x01(\x05R\fminIdleConns\x12*\n" +
	"\x11max_conn_lifetime\x18\x03 \x01(\x03R\x0fmaxConnLifetime\x12+\n" +
	"\x12max_conn_idle_time\x18\x04 \x01(\x03R\x0fmaxConnIdleTime\x1a\xb3\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\"\x93\x0f\n" +
	"\n" +
	"Moderation\x12/\n" +
	"\x04vllm\x18\x01 \x01(\v2\x1b.kratos.api.Moderation.VLLMR\x04vllm\x122\n" +
	"\x05phash\x18\x02 \x01(\v2\x1c.kratos.api.Moderation.PHashR\x05phash\x129\n" +
	"\x04text\x18\x03 \x01(\v2%.kratos.api.Moderation.TextModerationR\x04text\x127\n" +
	"\x04nsfw\x18\x04 \x01(\v2#.kratos.api.Moderation.NSFWDetectorR\x04nsfw\x12>\n" +
	"\tmoderator\x18\x05 \x01(\v2 .kratos.api.Moderation.ModeratorR\tmoderator\x1a\x86\x01\n" +
	"\x04VLLM\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1aT\n" +
	"\x05PHash\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x121\n" +
	"\x14similarity_threshold\x18\x02 \x01(\x05R\x13similarityThreshold\x1af\n" +
	"\x0eTextModeration\x12)\n" +
	"\x10reject_threshold\x18\x01 \x01(\x05R\x0frejectThreshold\x12)\n" +
	"\x10review_threshold\x18\x02 \x01(\x05R\x0freviewThreshold\x1a\x8f\x01\n" +
	"\fNSFWDetector\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x02R\tthreshold\x1a\x92\t\n" +
	"\tModerator\x12X\n" +
	"\x0fimage_moderator\x18\x01 \x01(\v2/.kratos.api.Moderation.Moderator.ImageModeratorR\x0eimageModerator\x12U\n" +
	"\x0etext_moderator\x18\x02 \x01(\v2..kratos.api.Moderation.Moderator.TextModeratorR\rtextModerator\x12X\n" +
	"\x0fvideo_moderator\x18\x03 \x01(\v2/.kratos.api.Moderation.Moderator.VideoModeratorR\x0evideoModerator\x1a\xba\x02\n" +
	"\x0eImageModerator\x12\x18\n" +
	"\aworkers\x18\x01 \x01(\x05R\aworkers\x12%\n" +
	"\x0ensfw_threshold\x18\x02 \x01(\x02R\rnsfwThreshold\x12-\n" +
	"\x12violence_threshold\x18\x03 \x01(\x02R\x11violenceThreshold\x12\x1d\n" +
	"\n" +
	"enable_ocr\x18\x04 \x01(\bR\tenableOcr\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1d\n" +
	"\n" +
	"bloom_bits\x18\x06 \x01(\rR\tbloomBits\x12(\n" +
	"\x10bloom_hash_funcs\x18\a \x01(\rR\x0ebloomHashFuncs\x12\x1b\n" +
	"\tbloom_key\x18\b \x01(\tR\bbloomKey\x1a\xeb\x02\n" +
	"\rTextModerator\x12\x1d\n" +
	"\n" +
	"bloom_bits\x18\x01 \x01(\rR\tbloomBits\x12(\n" +
	"\x10bloom_hash_funcs\x18\x02 \x01(\rR\x0ebloomHashFuncs\x12\x1b\n" +
	"\tbloom_key\x18\x03 \x01(\tR\bbloomKey\x12)\n" +
	"\x10reject_threshold\x18\x04 \x01(\x05R\x0frejectThreshold\x12)\n" +
	"\x10review_threshold\x18\x05 \x01(\x05R\x0freviewThreshold\x12\x1d\n" +
	"\n" +
	"enable_llm\x18\x06 \x01(\bR\tenableLlm\x12\"\n" +
	"\rvllm_base_url\x18\a \x01(\tR\vvllmBaseUrl\x12\x1d\n" +
	"\n" +
	"vllm_model\x18\b \x01(\tR\tvllmModel\x12<\n" +
	"\fvllm_timeout\x18\t \x01(\v2\x19.google.protobuf.DurationR\vvllmTimeout\x1a\xce\x01\n" +
	"\x0eVideoModerator\x12*\n" +
	"\x11frame_sample_rate\x18\x01 \x01(\x05R\x0fframeSampleRate\x12-\n" +
	"\x13max_frames_to_check\x18\x02 \x01(\x05R\x10maxFramesToCheck\x12,\n" +
	"\x12enable_audio_check\x18\x03 \x01(\bR\x10enableAudioCheck\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeoutB\x1fZ\x1dmoderation/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),                           // 0: kratos.api.Bootstrap
	(*Server)(nil),                              // 1: kratos.api.Server
	(*Data)(nil),                                // 2: kratos.api.Data
	(*Moderation)(nil),                          // 3: kratos.api.Moderation
	(*Server_HTTP)(nil),                         // 4: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),                         // 5: kratos.api.Server.GRPC
	(*Data_Database)(nil),                       // 6: kratos.api.Data.Database
	(*Data_Redis)(nil),                          // 7: kratos.api.Data.Redis
	(*Data_Database_Pool)(nil),                  // 8: kratos.api.Data.Database.Pool
	(*Moderation_VLLM)(nil),                     // 9: kratos.api.Moderation.VLLM
	(*Moderation_PHash)(nil),                    // 10: kratos.api.Moderation.PHash
	(*Moderation_TextModeration)(nil),           // 11: kratos.api.Moderation.TextModeration
	(*Moderation_NSFWDetector)(nil),             // 12: kratos.api.Moderation.NSFWDetector
	(*Moderation_Moderator)(nil),                // 13: kratos.api.Moderation.Moderator
	(*Moderation_Moderator_ImageModerator)(nil), // 14: kratos.api.Moderation.Moderator.ImageModerator
	(*Moderation_Moderator_TextModerator)(nil),  // 15: kratos.api.Moderation.Moderator.TextModerator
	(*Moderation_Moderator_VideoModerator)(nil), // 16: kratos.api.Moderation.Moderator.VideoModerator
	(*durationpb.Duration)(nil),                 // 17: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.moderation:type_name -> kratos.api.Moderation
	4,  // 3: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	5,  // 4: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	6,  // 5: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	7,  // 6: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	9,  // 7: kratos.api.Moderation.vllm:type_name -> kratos.api.Moderation.VLLM
	10, // 8: kratos.api.Moderation.phash:type_name -> kratos.api.Moderation.PHash
	11, // 9: kratos.api.Moderation.text:type_name -> kratos.api.Moderation.TextModeration
	12, // 10: kratos.api.Moderation.nsfw:type_name -> kratos.api.Moderation.NSFWDetector
	13, // 11: kratos.api.Moderation.moderator:type_name -> kratos.api.Moderation.Moderator
	17, // 12: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	17, // 13: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	8,  // 14: kratos.api.Data.Database.pool:type_name -> kratos.api.Data.Database.Pool
	17, // 15: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	17, // 16: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	17, // 17: kratos.api.Moderation.VLLM.timeout:type_name -> google.protobuf.Duration
	17, // 18: kratos.api.Moderation.NSFWDetector.timeout:type_name -> google.protobuf.Duration
	14, // 19: kratos.api.Moderation.Moderator.image_moderator:type_name -> kratos.api.Moderation.Moderator.ImageModerator
	15, // 20: kratos.api.Moderation.Moderator.text_moderator:type_name -> kratos.api.Moderation.Moderator.TextModerator
	16, // 21: kratos.api.Moderation.Moderator.video_moderator:type_name -> kratos.api.Moderation.Moderator.VideoModerator
	17, // 22: kratos.api.Moderation.Moderator.ImageModerator.timeout:type_name -> google.protobuf.Duration
	17, // 23: kratos.api.Moderation.Moderator.TextModerator.vllm_timeout:type_name -> google.protobuf.Duration
	17, // 24: kratos.api.Moderation.Moderator.VideoModerator.timeout:type_name -> google.protobuf.Duration
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
