// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: nsfw.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NSFWDetector_Predict_FullMethodName              = "/nsfw.v1.NSFWDetector/Predict"
	NSFWDetector_PredictFromURL_FullMethodName       = "/nsfw.v1.NSFWDetector/PredictFromURL"
	NSFWDetector_PredictBatchFromURLs_FullMethodName = "/nsfw.v1.NSFWDetector/PredictBatchFromURLs"
	NSFWDetector_HealthCheck_FullMethodName          = "/nsfw.v1.NSFWDetector/HealthCheck"
)

// NSFWDetectorClient is the client API for NSFWDetector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NSFWDetector service for detecting NSFW content in images.
type NSFWDetectorClient interface {
	// Predict NSFW content from raw image bytes.
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	// Predict NSFW content from a public image URL.
	PredictFromURL(ctx context.Context, in *PredictURLRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	// Predict NSFW content for a batch of images (by URL).
	PredictBatchFromURLs(ctx context.Context, in *PredictBatchURLRequest, opts ...grpc.CallOption) (*PredictBatchResponse, error)
	// Health check.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type nSFWDetectorClient struct {
	cc grpc.ClientConnInterface
}

func NewNSFWDetectorClient(cc grpc.ClientConnInterface) NSFWDetectorClient {
	return &nSFWDetectorClient{cc}
}

func (c *nSFWDetectorClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, NSFWDetector_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSFWDetectorClient) PredictFromURL(ctx context.Context, in *PredictURLRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, NSFWDetector_PredictFromURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSFWDetectorClient) PredictBatchFromURLs(ctx context.Context, in *PredictBatchURLRequest, opts ...grpc.CallOption) (*PredictBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictBatchResponse)
	err := c.cc.Invoke(ctx, NSFWDetector_PredictBatchFromURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nSFWDetectorClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NSFWDetector_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NSFWDetectorServer is the server API for NSFWDetector service.
// All implementations must embed UnimplementedNSFWDetectorServer
// for forward compatibility.
//
// NSFWDetector service for detecting NSFW content in images.
type NSFWDetectorServer interface {
	// Predict NSFW content from raw image bytes.
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	// Predict NSFW content from a public image URL.
	PredictFromURL(context.Context, *PredictURLRequest) (*PredictResponse, error)
	// Predict NSFW content for a batch of images (by URL).
	PredictBatchFromURLs(context.Context, *PredictBatchURLRequest) (*PredictBatchResponse, error)
	// Health check.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedNSFWDetectorServer()
}

// UnimplementedNSFWDetectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNSFWDetectorServer struct{}

func (UnimplementedNSFWDetectorServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedNSFWDetectorServer) PredictFromURL(context.Context, *PredictURLRequest) (*PredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictFromURL not implemented")
}
func (UnimplementedNSFWDetectorServer) PredictBatchFromURLs(context.Context, *PredictBatchURLRequest) (*PredictBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictBatchFromURLs not implemented")
}
func (UnimplementedNSFWDetectorServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNSFWDetectorServer) mustEmbedUnimplementedNSFWDetectorServer() {}
func (UnimplementedNSFWDetectorServer) testEmbeddedByValue()                      {}

// UnsafeNSFWDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NSFWDetectorServer will
// result in compilation errors.
type UnsafeNSFWDetectorServer interface {
	mustEmbedUnimplementedNSFWDetectorServer()
}

func RegisterNSFWDetectorServer(s grpc.ServiceRegistrar, srv NSFWDetectorServer) {
	// If the following call pancis, it indicates UnimplementedNSFWDetectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NSFWDetector_ServiceDesc, srv)
}

func _NSFWDetector_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWDetectorServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFWDetector_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWDetectorServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSFWDetector_PredictFromURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWDetectorServer).PredictFromURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFWDetector_PredictFromURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWDetectorServer).PredictFromURL(ctx, req.(*PredictURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSFWDetector_PredictBatchFromURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictBatchURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWDetectorServer).PredictBatchFromURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFWDetector_PredictBatchFromURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWDetectorServer).PredictBatchFromURLs(ctx, req.(*PredictBatchURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NSFWDetector_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NSFWDetectorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NSFWDetector_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NSFWDetectorServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NSFWDetector_ServiceDesc is the grpc.ServiceDesc for NSFWDetector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NSFWDetector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nsfw.v1.NSFWDetector",
	HandlerType: (*NSFWDetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _NSFWDetector_Predict_Handler,
		},
		{
			MethodName: "PredictFromURL",
			Handler:    _NSFWDetector_PredictFromURL_Handler,
		},
		{
			MethodName: "PredictBatchFromURLs",
			Handler:    _NSFWDetector_PredictBatchFromURLs_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NSFWDetector_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nsfw.proto",
}
