# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/nsfw_text.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/nsfw_text.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/nsfw_text.proto\x12\x0cnsfw_text.v1\"\x1e\n\x0ePredictRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"$\n\x13PredictBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"L\n\x0fPredictResponse\x12\x0f\n\x07is_nsfw\x18\x01 \x01(\x08\x12\x14\n\x0csafety_label\x18\x02 \x01(\t\x12\x12\n\ncategories\x18\x03 \x03(\t\"c\n\x15\x42\x61tchPredictionResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12-\n\x06result\x18\x02 \x01(\x0b\x32\x1d.nsfw_text.v1.PredictResponse\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"P\n\x14PredictBatchResponse\x12\x38\n\x0bpredictions\x18\x01 \x03(\x0b\x32#.nsfw_text.v1.BatchPredictionResult\"\x14\n\x12HealthCheckRequest\"D\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t2\x85\x02\n\x10NSFWTextDetector\x12\x46\n\x07Predict\x12\x1c.nsfw_text.v1.PredictRequest\x1a\x1d.nsfw_text.v1.PredictResponse\x12U\n\x0cPredictBatch\x12!.nsfw_text.v1.PredictBatchRequest\x1a\".nsfw_text.v1.PredictBatchResponse\x12R\n\x0bHealthCheck\x12 .nsfw_text.v1.HealthCheckRequest\x1a!.nsfw_text.v1.HealthCheckResponseB Z\x1emoderation/api/nsfw_text/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.nsfw_text_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036moderation/api/nsfw_text/v1;v1'
  _globals['_PREDICTREQUEST']._serialized_start=39
  _globals['_PREDICTREQUEST']._serialized_end=69
  _globals['_PREDICTBATCHREQUEST']._serialized_start=71
  _globals['_PREDICTBATCHREQUEST']._serialized_end=107
  _globals['_PREDICTRESPONSE']._serialized_start=109
  _globals['_PREDICTRESPONSE']._serialized_end=185
  _globals['_BATCHPREDICTIONRESULT']._serialized_start=187
  _globals['_BATCHPREDICTIONRESULT']._serialized_end=286
  _globals['_PREDICTBATCHRESPONSE']._serialized_start=288
  _globals['_PREDICTBATCHRESPONSE']._serialized_end=368
  _globals['_HEALTHCHECKREQUEST']._serialized_start=370
  _globals['_HEALTHCHECKREQUEST']._serialized_end=390
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=392
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=460
  _globals['_NSFWTEXTDETECTOR']._serialized_start=463
  _globals['_NSFWTEXTDETECTOR']._serialized_end=724
# @@protoc_insertion_point(module_scope)
